/**Práctica Final Patrones de Software 2015/2016
 * Agencia de Busqueda de Empleo
 *Alumnos: Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 * Clase BusquedaCandidatoParaOferta
 */
package AgenciaSwing;

import AgenciaEmpleo.AdaptadorSueldo;
import AgenciaEmpleo.Agregado;
import AgenciaEmpleo.AgregadoConcreto;
import AgenciaEmpleo.EstadoDisponible;
import AgenciaEmpleo.Iterador;
import AgenciaEmpleo.Oferta;
import AgenciaEmpleo.OfertaAbstracta;
import AgenciaEmpleo.OfertaImp;
import AgenciaEmpleo.OfertaImpClave;
import AgenciaEmpleo.OfertaImpCno;
import AgenciaEmpleo.Oficina;
import AgenciaEmpleo.Sueldo;
import AgenciaEmpleo.UtilSistema;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.ListIterator;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 * El empleado visualizará las ofertas con los datos correspondientes
 * Pudiendo ir hacia adelante o hacia atrás para ver cada uno de las ofertas
 * disponibles A su vez mediante el botón 'BusquedaCandidatos' alegirá el tipo de busqueda
 * @author Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 */
public class BusquedaCandidatoParaOferta extends javax.swing.JFrame {

    private Oferta of;
    private Oficina ofi;
    private ListIterator ite;//utilizamos un ListIterator ya que queremos recorrerlo en ambas direcciones 
    private ArrayList<Oferta> ofAux;
    private OfertaAbstracta abs;
    
    //Uso patron ITERATOR
    // Crea el agregado.
    Agregado agregado = new AgregadoConcreto(UtilSistema.getOfertas().toArray());
     // Crea el iterador.
    Iterador iterador = agregado.crearIterador();
    
    //PARA ADAPTER
    private Sueldo s ;

    /**
     * Constructor
     */
    public BusquedaCandidatoParaOferta() {
        initComponents();
        this.setLocationRelativeTo(null);//Centramos la pantalla
        PanelFondo F = new PanelFondo(); //Creamos el objeto F de tipo PanelFondo
        this.add(F, BorderLayout.CENTER);
        this.pack();
        verOfertas();
        abs = new OfertaAbstracta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldLetra = new javax.swing.JTextField();
        jLabelLetra = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jTextFieldLoca = new javax.swing.JTextField();
        jLabelLoca = new javax.swing.JLabel();
        jTextFieldDedicacion = new javax.swing.JTextField();
        jTextFieldCodPos = new javax.swing.JTextField();
        jLabelDedicacion = new javax.swing.JLabel();
        jLabelCodPos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxJornada = new javax.swing.JCheckBox();
        Date dateC = new Date();
        SpinnerDateModel ca =
        new SpinnerDateModel(dateC, null, null, Calendar.DATE);
        jSpinnerFechaAper = new javax.swing.JSpinner(ca);
        JSpinner.DateEditor cadu = new JSpinner.DateEditor(jSpinnerFechaAper,"DD/MM/yyyy");
        jSpinnerFechaAper.setEditor(cadu);
        jSpinnerFechaCadu = new javax.swing.JSpinner(ca);
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.DATE);
        jSpinnerFechaAper = new javax.swing.JSpinner(sm);
        jLabelFehcaCadu = new javax.swing.JLabel();
        jTextFieldNomCompañia = new javax.swing.JTextField();
        jLabelFechaAper = new javax.swing.JLabel();
        jLabelNomCompañia = new javax.swing.JLabel();
        jTextFieldTlf = new javax.swing.JTextField();
        jLabelTlf = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jLabelNomOficina = new javax.swing.JLabel();
        jTextFieldNomOficina = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelNum = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jLabelOcupaciones = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCan = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();
        jButtonSig = new javax.swing.JButton();
        VolverMenuP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSalMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSalMax = new javax.swing.JTextField();
        jTextFieldOcupaciones = new javax.swing.JTextField();
        jLabelClaves = new javax.swing.JLabel();
        jTextFieldClaves = new javax.swing.JTextField();
        jButtonDisponible = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSueldoNeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agencia de Empleo - Busqueda de Candidatos para Oferta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e-Business.jpg"))); // NOI18N
        Logo.setText("jLabel5");

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelTitulo.setText("AGENCIA DE EMPLEO");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setAlignmentX(0.5F);
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jTextFieldLetra.setEditable(false);
        jTextFieldLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLetraKeyTyped(evt);
            }
        });

        jLabelLetra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLetra.setText("Letra");

        jTextFieldPiso.setEditable(false);
        jTextFieldPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPisoKeyTyped(evt);
            }
        });

        jTextFieldLoca.setEditable(false);

        jLabelLoca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLoca.setText("Localidad");

        jTextFieldDedicacion.setEditable(false);
        jTextFieldDedicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDedicacionActionPerformed(evt);
            }
        });
        jTextFieldDedicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDedicacionKeyTyped(evt);
            }
        });

        jTextFieldCodPos.setEditable(false);
        jTextFieldCodPos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodPosKeyTyped(evt);
            }
        });

        jLabelDedicacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDedicacion.setText("Tiempo de Dedicación");

        jLabelCodPos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelCodPos.setText("Código Postal");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Si su jornada no es Completa seleccione la siguiente casilla");

        jCheckBoxJornada.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBoxJornada.setText("Jornada Laboral Parcial");
        jCheckBoxJornada.setEnabled(false);

        jSpinnerFechaCadu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jSpinnerFechaCadu.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(978303600000L), new java.util.Date(1924902000000L), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFechaCadu.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaCadu, "d/MM/yyyy"));

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinnerFechaAper,"DD/MM/yyyy");
        jSpinnerFechaAper.setEditor(de);
        jSpinnerFechaAper.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jSpinnerFechaAper.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(978303600000L), new java.util.Date(1924902000000L), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFechaAper.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAper, "d/MM/yyyy"));

        jLabelFehcaCadu.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelFehcaCadu.setText("Fecha Caducidad");

        jTextFieldNomCompañia.setEditable(false);
        jTextFieldNomCompañia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomCompañiaKeyTyped(evt);
            }
        });

        jLabelFechaAper.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelFechaAper.setText("Fecha Apertura");

        jLabelNomCompañia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNomCompañia.setText("Nombre Compañía");

        jTextFieldTlf.setEditable(false);
        jTextFieldTlf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTlfKeyTyped(evt);
            }
        });

        jLabelTlf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelTlf.setText("Telefono");

        jLabelSueldo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelSueldo.setText("Rango Salarial");

        jLabelNomOficina.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNomOficina.setText("Oficina");

        jTextFieldNomOficina.setEditable(false);
        jTextFieldNomOficina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomOficinaKeyTyped(evt);
            }
        });

        jLabelDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDireccion.setText("Direccion");

        jTextFieldDireccion.setEditable(false);

        jLabelNum.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNum.setText("Nº");

        jTextFieldNum.setEditable(false);
        jTextFieldNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumKeyTyped(evt);
            }
        });

        jLabelPiso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPiso.setText("Piso");

        jLabelOcupaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelOcupaciones.setText("Categorías de Empleo");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Búsqueda de Candidatos para la empresa");

        jButtonCan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonCan.setText("BUSCAR CANDIDATO");
        jButtonCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanActionPerformed(evt);
            }
        });

        jButtonAnt.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonAnt.setText("ANTERIOR");
        jButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntActionPerformed(evt);
            }
        });

        jButtonSig.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonSig.setText("SIGUIENTE");
        jButtonSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSigActionPerformed(evt);
            }
        });

        VolverMenuP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        VolverMenuP.setForeground(new java.awt.Color(0, 102, 255));
        VolverMenuP.setText("ATRÁS");
        VolverMenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Salario Mínimo");

        jTextFieldSalMin.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Salario Máximo");

        jTextFieldSalMax.setEditable(false);

        jTextFieldOcupaciones.setEditable(false);
        jTextFieldOcupaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOcupacionesActionPerformed(evt);
            }
        });

        jLabelClaves.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelClaves.setText("Palabras Claves");

        jTextFieldClaves.setEditable(false);

        jButtonDisponible.setText("Cambiar a Disponible");
        jButtonDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisponibleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Salario Neto Mensual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabelNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPiso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLetra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelDireccion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelTlf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelNomOficina)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNomOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelNomCompañia)
                                    .addGap(56, 56, 56)
                                    .addComponent(jTextFieldNomCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelClaves)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldClaves))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelLoca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCodPos)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jCheckBoxJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDedicacion)
                                .addGap(25, 25, 25)
                                .addComponent(jTextFieldDedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelSueldo)
                                    .addComponent(jLabel4))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSalMin)
                                    .addComponent(jTextFieldSalMax, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSueldoNeto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFechaAper, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFehcaCadu)
                                    .addComponent(jLabelOcupaciones))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerFechaAper)
                                    .addComponent(jSpinnerFechaCadu)
                                    .addComponent(jTextFieldOcupaciones))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(97, 97, 97)
                        .addComponent(jButtonCan)
                        .addGap(212, 212, 212)
                        .addComponent(jButtonDisponible)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VolverMenuP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButtonAnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSig))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSueldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSueldoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomCompañia)
                            .addComponent(jTextFieldNomCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldSalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomOficina)
                            .addComponent(jTextFieldNomOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldSalMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTlf)
                                    .addComponent(jTextFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDireccion)
                                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNum)
                                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPiso)
                                    .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLetra)
                                    .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCodPos)
                                        .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelLoca))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelClaves)
                                    .addComponent(jTextFieldClaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxJornada)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDedicacion)
                                    .addComponent(jTextFieldDedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelOcupaciones)
                                    .addComponent(jTextFieldOcupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFechaAper)
                                    .addComponent(jSpinnerFechaAper, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFehcaCadu)
                                    .addComponent(jSpinnerFechaCadu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSig)
                    .addComponent(jButtonAnt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCan)
                        .addComponent(jButtonDisponible)))
                .addGap(12, 12, 12)
                .addComponent(VolverMenuP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLetraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLetraKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLetraKeyTyped

    private void jTextFieldPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPisoKeyTyped
        //Prevenimos que el usuario introduzca letras en el campo del piso
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPisoKeyTyped

    private void jTextFieldDedicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDedicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDedicacionActionPerformed

    private void jTextFieldDedicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDedicacionKeyTyped
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDedicacionKeyTyped

    private void jTextFieldCodPosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodPosKeyTyped
        // TODO add your handling code here:
        int limite = 5;
        if (jTextFieldCodPos.getText().length() == limite) {
            evt.consume();//Una vez se halla introducido 5 dígitos el resto serán capturados y almacenados en la variable evt
        }
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodPosKeyTyped

    private void jTextFieldNomCompañiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomCompañiaKeyTyped
    }//GEN-LAST:event_jTextFieldNomCompañiaKeyTyped

    private void jTextFieldTlfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTlfKeyTyped
        // Prevenimos que el usuario introduzca letras en el campo de Telefono
        /*Para ello mediante el evento evt.getKeyChar
         * cuando el usuario pulse una letra no la reconozca y por tanto no se escriba
         Por ello cada caracter que presione el usuario se almacena en la variable evt  */
        int limite = 9;//atributo que limita el número de caracteres a introducir en el campo del telefono
        if (jTextFieldTlf.getText().length() == limite) {
            evt.consume();//Una vez se halla introducido 9 dígitos el resto serán capturados y almacenados en la variable evt
        }
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTlfKeyTyped

    private void jTextFieldNomOficinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomOficinaKeyTyped
    }//GEN-LAST:event_jTextFieldNomOficinaKeyTyped

    private void jTextFieldNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumKeyTyped
        //Prevenimos que el usuario introduzca letras en el campo del número de edificio
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumKeyTyped
    /**
     * Permite visualizar los datos con los botones Anterior y Siguiente
     */
    private void verOfertas() {
        try {
            ofAux = UtilSistema.getOfertas();//Array igual que el array de ofertas
            ite = ofAux.listIterator();//Iterator para recorrer las ofertas

            if (ofAux.size() < 1) {//Si el tamaño es menor que uno lanza un error
                JOptionPane.showMessageDialog(this, "Error, no hay ofertas", "ERROR", JOptionPane.ERROR_MESSAGE);
                jButtonAnt.setEnabled(false);
                jButtonSig.setEnabled(false);
            } else {
                jButtonAnt.setEnabled(true);
                jButtonSig.setEnabled(true);
            }

            if (iterador.hayMas()) {//Si hay ofertas las convierte a objeto 
                of = (Oferta) iterador.siguiente();

            }
            if (of != null) {//Si no es nula la presenta
                verDatos(of);
            } else {//No hay mas ofertas
                JOptionPane.showMessageDialog(this, "No hay mas ofertas", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
     /**
     * Permite buscar ofertas que casen con candidatos
     */
    private void jButtonCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanActionPerformed
        String[] opciones = {"CNO", "Claves"};

        int n;
        n = JOptionPane.showOptionDialog(this,
                "Tipo de Búsqueda",
                "¿Cómo realizar la búsqueda?",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]);
        if (n == JOptionPane.YES_OPTION) {
            OfertaImp imp = new OfertaImpCno();
            abs.setImp(imp);
             if (abs.buscar(of)) {
                    JOptionPane.showMessageDialog(this, "Se han encontrado : " + UtilSistema.getCandiCasan().size() + " coincidencias. "+of.getOficina().getNomCompañia(), "EXITO", JOptionPane.INFORMATION_MESSAGE);
                    CanParaOf a = new CanParaOf(this);
                } else {//Si es falso se no se han encontrado coincidencias
                    JOptionPane.showMessageDialog(this, "No se han encontrado coincidencias", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }
        } else if (n == JOptionPane.NO_OPTION) {
            OfertaImp imp = new OfertaImpClave();
            abs.setImp(imp);
            if (abs.buscar(of)) {
                    JOptionPane.showMessageDialog(this, "Se han encontrado: " + UtilSistema.getCandiCasan().size()+ " coincidencias.", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                    CanParaOf b = new CanParaOf(this);
                } else {//si es falso no se han encontrado coincidencias
                    JOptionPane.showMessageDialog(this, "No se han encontrado coincidencias", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }
        } else if (n == JOptionPane.CANCEL_OPTION) {
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCanActionPerformed
    /**
     * Permite visualizar los datos de las ofertas
     */
    private void verDatos(Oferta of) {

        String tipo;
        String claves = "";
        for (int i = 0; i < of.getClaves().length; i++) {
            claves += of.getClaves()[i] + ",";//Obtiene las claves

        }
         //PARA ADAPTER
        s = new AdaptadorSueldo(of);
        
        jTextFieldNomCompañia.setText(of.getOficina().getNomCompañia());
        jTextFieldNomOficina.setText(of.getOficina().getNomOficina());
        jTextFieldTlf.setText(Integer.toString(of.getOficina().getTlf()));
        jTextFieldDireccion.setText(of.getOficina().getDireccion().getNombre());
        jTextFieldNum.setText(Integer.toString(of.getOficina().getDireccion().getNumero()));
        jTextFieldPiso.setText(Integer.toString(of.getOficina().getDireccion().getPiso()));
        jTextFieldLetra.setText(of.getOficina().getDireccion().getLetra());
        jTextFieldLoca.setText(of.getOficina().getDireccion().getLocalidad());
        jTextFieldCodPos.setText(Integer.toString(of.getOficina().getDireccion().getCodigoPostal()));
        jTextFieldOcupaciones.setText(of.getOcupacion().toString());
        jTextFieldClaves.setText(claves);
        jTextFieldSalMin.setText(Double.toString(of.getSalMin()));
        jTextFieldSalMax.setText(Double.toString(of.getSalMax()));
        //PARA ADAPTER
        jTextFieldSueldoNeto.setText(s.getSueldoNeto());
        if (of.getTipo().equals("Parcial")) {
            jLabelDedicacion.setVisible(true);
            jTextFieldDedicacion.setVisible(true);
            jTextFieldDedicacion.setText(Double.toString(of.getGrado()));
        } else {
            jLabelDedicacion.setVisible(false);
            jTextFieldDedicacion.setVisible(false);
        }
        
       of.cambiar(this);
        
        
    }
    /**
     * Permite no visualizar los campos de datos
     */  
    public void anularText(){
    jTextFieldNomCompañia.setEnabled(false);
        jTextFieldNomOficina.setEnabled(false);
        jTextFieldTlf.setEnabled(false);
        jTextFieldDireccion.setEnabled(false);
        jTextFieldNum.setEnabled(false);
        jTextFieldPiso.setEnabled(false);
        jTextFieldLetra.setEnabled(false);
        jTextFieldLoca.setEnabled(false);
        jTextFieldCodPos.setEnabled(false);
        jTextFieldOcupaciones.setEnabled(false);
        jTextFieldClaves.setEnabled(false);
        jTextFieldSalMin.setEnabled(false);
        jTextFieldSalMax.setEnabled(false);
        jLabelDedicacion.setVisible(false);
            jTextFieldDedicacion.setVisible(false);
            jButtonDisponible.setEnabled(true);
    }
     /**
     * Permite visualizar los datos 
     */   
    public void habilitarText(){
        jTextFieldNomCompañia.setEnabled(true);
        jTextFieldNomOficina.setEnabled(true);
        jTextFieldTlf.setEnabled(true);
        jTextFieldDireccion.setEnabled(true);
        jTextFieldNum.setEnabled(true);
        jTextFieldPiso.setEnabled(true);
        jTextFieldLetra.setEnabled(true);
        jTextFieldLoca.setEnabled(true);
        jTextFieldCodPos.setEnabled(true);
        jTextFieldOcupaciones.setEnabled(true);
        jTextFieldClaves.setEnabled(true);
        jTextFieldSalMin.setEnabled(true);
        jTextFieldSalMax.setEnabled(true);
        jLabelDedicacion.setVisible(true);
            jTextFieldDedicacion.setVisible(true);
            jButtonDisponible.setEnabled(false);
            
    
    }
    /*Con el siguiente botón el empleado podrá visualizar las ofertas
     * Mediante un iterator recorrerá el array de Ofertas 
     * Pudiendo ir hacia atrás, hasta que no halla más candidatos en el array
     */
    private void jButtonAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntActionPerformed
        if (iterador.hayAnterior()) {
            of = (Oferta) iterador.anterior();
        }
        //Si hay candidatos podrá ir atrás y visualizar los datos en los campos correspondientes
        if (of != null) {
            verDatos(of);
        } else {
            JOptionPane.showMessageDialog(this, "No se encuentran más ofertas disponibles");
        }

    }//GEN-LAST:event_jButtonAntActionPerformed
    /*Con el siguiente botón el empleado podrá visualizar las ofertas
     * Mediante un iterator recorrerá el array de Ofertas 
     * Pudiendo ir hacia adelante, hasta que no halla más candidatos en el array
     */
    private void jButtonSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSigActionPerformed
        if (iterador.hayMas()) {//Recorremos el array con el iterator
            of = (Oferta) iterador.siguiente();
            
        }
        //Si hay candidatos
        if (of != null) {
            verDatos(of);
            // getImagen(can);
        } else {
            JOptionPane.showMessageDialog(this, "No hay candidatos dados de alta");
        }
    }//GEN-LAST:event_jButtonSigActionPerformed

    private void VolverMenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPActionPerformed
        UtilSistema.guardarDatos();
        Empleado ventana = new Empleado();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuPActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       UtilSistema.guardarDatos();
        this.setVisible(false);
        Empleado principal = new Empleado();
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    /**
     * Cambia el estado de la oferta
     */
    private void jButtonDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisponibleActionPerformed
      
        int indice = UtilSistema.ofertas.indexOf(of);
        
        UtilSistema.ofertas.get(indice).setEstadoActual(new EstadoDisponible());
        UtilSistema.ofertas.get(indice).cambiar(this);
    
    }//GEN-LAST:event_jButtonDisponibleActionPerformed
   
    
    private void jTextFieldOcupacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOcupacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOcupacionesActionPerformed
    
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaCandidatoParaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaCandidatoParaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaCandidatoParaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaCandidatoParaOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaCandidatoParaOferta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton VolverMenuP;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonCan;
    private javax.swing.JButton jButtonDisponible;
    private javax.swing.JButton jButtonSig;
    private javax.swing.JCheckBox jCheckBoxJornada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClaves;
    private javax.swing.JLabel jLabelCodPos;
    private javax.swing.JLabel jLabelDedicacion;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFechaAper;
    private javax.swing.JLabel jLabelFehcaCadu;
    private javax.swing.JLabel jLabelLetra;
    private javax.swing.JLabel jLabelLoca;
    private javax.swing.JLabel jLabelNomCompañia;
    private javax.swing.JLabel jLabelNomOficina;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelOcupaciones;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTlf;
    private javax.swing.JSpinner jSpinnerFechaAper;
    private javax.swing.JSpinner jSpinnerFechaCadu;
    public static javax.swing.JTextField jTextFieldClaves;
    public static javax.swing.JTextField jTextFieldCodPos;
    private javax.swing.JTextField jTextFieldDedicacion;
    public static javax.swing.JTextField jTextFieldDireccion;
    public static javax.swing.JTextField jTextFieldLetra;
    public static javax.swing.JTextField jTextFieldLoca;
    private javax.swing.JTextField jTextFieldNomCompañia;
    public static javax.swing.JTextField jTextFieldNomOficina;
    public static javax.swing.JTextField jTextFieldNum;
    public static javax.swing.JTextField jTextFieldOcupaciones;
    public static javax.swing.JTextField jTextFieldPiso;
    public static javax.swing.JTextField jTextFieldSalMax;
    public static javax.swing.JTextField jTextFieldSalMin;
    public static javax.swing.JTextField jTextFieldSueldoNeto;
    public static javax.swing.JTextField jTextFieldTlf;
    // End of variables declaration//GEN-END:variables
}
