/**Práctica Final Patrones de Software 2015/2016
 * Agencia de Busqueda de Empleo
 *Alumnos: Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 * Clase OfParaCan
 */
package AgenciaSwing;

import AgenciaEmpleo.Agregado;
import AgenciaEmpleo.AgregadoConcreto;
import AgenciaEmpleo.Iterador;
import AgenciaEmpleo.Oferta;
import AgenciaEmpleo.Oficina;
import AgenciaEmpleo.Proxy;
import AgenciaEmpleo.Servidor;
import AgenciaEmpleo.ServidorFicheros;
import AgenciaEmpleo.UtilSistema;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.ListIterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 */
public class OfParaCan extends javax.swing.JFrame {

    private Oferta of;
    private Oficina ofi;
    private ListIterator ite;
    private ArrayList<Oferta> ofAux;
    private JFrame principal;
    //Patron Proxy
    private static Servidor proxy = new Proxy(new ServidorFicheros("MiServidor"));
    
    //Uso patron ITERATOR
    // Crea el agregado.
    Agregado agregado = new AgregadoConcreto(UtilSistema.getOfertas().toArray());
     // Crea el iterador.
    Iterador iterador = agregado.crearIterador();

    /**
     * Constructor
     * @param ventana
     */
    public OfParaCan(JFrame ventana) {
        initComponents();
        verOfertas();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);//Centramos la pantalla
        PanelFondo F = new PanelFondo(); //Creamos el objeto F de tipo PanelFondo
        this.add(F, BorderLayout.CENTER);
        this.pack();
        
    }
    /**
     * Visualiza las ofertas con los botones anterior y siguiente
     */
    private void verOfertas() {
        try {
            ofAux = UtilSistema.getOfertas();//Array igual que el array de ofertas
            ite = ofAux.listIterator();//Iterator para recorrer las ofertas

            if (ofAux.size() < 1) {//Si el tamaño es menor que uno lanza un error
                JOptionPane.showMessageDialog(this, "Error, no hay ofertas", "ERROR", JOptionPane.ERROR_MESSAGE);
                jButtonAnt.setEnabled(false);
                jButtonSig.setEnabled(false);
            } else {
                jButtonAnt.setEnabled(true);
                jButtonSig.setEnabled(true);
            }

            if (ite.hasNext()) {//Si hay ofertas las convierte a objeto 
                of = (Oferta) ite.next();

            }
            if (of != null) {//Si no es nula la presenta
                verDatos(of);
            } else {//No hay mas ofertas
                JOptionPane.showMessageDialog(this, "No hay mas ofertas", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Visualiza los datos de las ofertas
     */
    private void verDatos(Oferta of) {

        String tipo;
        String claves = "";
        for (int i = 0; i < of.getClaves().length; i++) {
            claves += of.getClaves()[i] + ",";//Obtiene las claves

        }
        jTextFieldNomCompañia.setText(of.getOficina().getNomCompañia());
        jTextFieldNomOficina.setText(of.getOficina().getNomOficina());
        jTextFieldTlf.setText(Integer.toString(of.getOficina().getTlf()));
        jTextFieldDireccion.setText(of.getOficina().getDireccion().getNombre());
        jTextFieldNum.setText(Integer.toString(of.getOficina().getDireccion().getNumero()));
        jTextFieldPiso.setText(Integer.toString(of.getOficina().getDireccion().getPiso()));
        jTextFieldLetra.setText(of.getOficina().getDireccion().getLetra());
        jTextFieldLoca.setText(of.getOficina().getDireccion().getLocalidad());
        jTextFieldCodPos.setText(Integer.toString(of.getOficina().getDireccion().getCodigoPostal()));
        jTextFieldOcupaciones.setText(of.getOcupacion().toString());
        jTextFieldClaves.setText(claves);
        jTextFieldSalMin.setText(Double.toString(of.getSalMin()));
        jTextFieldSalMax.setText(Double.toString(of.getSalMax()));
        if (of.getTipo().equals("Parcial")) {
            jLabelDedicacion.setVisible(true);
            jTextFieldDedicacion.setVisible(true);
            jTextFieldDedicacion.setText(Double.toString(of.getGrado()));
        } else {
            jLabelDedicacion.setVisible(false);
            jTextFieldDedicacion.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabelCodPos = new javax.swing.JLabel();
        jTextFieldClaves = new javax.swing.JTextField();
        jLabelClaves = new javax.swing.JLabel();
        jLabelLoca = new javax.swing.JLabel();
        jTextFieldCodPos = new javax.swing.JTextField();
        jTextFieldLetra = new javax.swing.JTextField();
        jLabelLetra = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jTextFieldLoca = new javax.swing.JTextField();
        jLabelNum = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldNomCompañia = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jTextFieldTlf = new javax.swing.JTextField();
        jLabelNomOficina = new javax.swing.JLabel();
        jLabelTlf = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelNomCompañia = new javax.swing.JLabel();
        jTextFieldNomOficina = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDedicacion = new javax.swing.JTextField();
        jLabelDedicacion = new javax.swing.JLabel();
        jCheckBoxJornada = new javax.swing.JCheckBox();
        jTextFieldSalMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSalMax = new javax.swing.JTextField();
        jTextFieldOcupaciones = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jLabelOcupaciones = new javax.swing.JLabel();
        jLabelFehcaCadu = new javax.swing.JLabel();
        Date dateC = new Date();
        SpinnerDateModel ca =
        new SpinnerDateModel(dateC, null, null, Calendar.DATE);
        jSpinnerFechaAper = new javax.swing.JSpinner(ca);
        JSpinner.DateEditor cadu = new JSpinner.DateEditor(jSpinnerFechaAper,"DD/MM/yyyy");
        jSpinnerFechaAper.setEditor(cadu);
        jSpinnerFechaCadu = new javax.swing.JSpinner(ca);
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.DATE);
        jSpinnerFechaAper = new javax.swing.JSpinner(sm);
        jLabelFechaAper = new javax.swing.JLabel();
        VolverMenuP = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();
        jButtonSig = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de Empleo - Ofertas para el candidato");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelTitulo.setText("AGENCIA DE EMPLEO");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setAlignmentX(0.5F);
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e-Business.jpg"))); // NOI18N
        Logo.setText("jLabel5");

        jLabelCodPos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelCodPos.setText("Código Postal");

        jTextFieldClaves.setEditable(false);
        jTextFieldClaves.setEnabled(false);

        jLabelClaves.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelClaves.setText("Palabras Claves");

        jLabelLoca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLoca.setText("Localidad");

        jTextFieldCodPos.setEditable(false);
        jTextFieldCodPos.setEnabled(false);
        jTextFieldCodPos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodPosKeyTyped(evt);
            }
        });

        jTextFieldLetra.setEditable(false);
        jTextFieldLetra.setEnabled(false);
        jTextFieldLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLetraKeyTyped(evt);
            }
        });

        jLabelLetra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLetra.setText("Letra");

        jTextFieldPiso.setEditable(false);
        jTextFieldPiso.setEnabled(false);
        jTextFieldPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPisoKeyTyped(evt);
            }
        });

        jTextFieldLoca.setEditable(false);
        jTextFieldLoca.setEnabled(false);

        jLabelNum.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNum.setText("Nº");

        jTextFieldDireccion.setEditable(false);
        jTextFieldDireccion.setEnabled(false);

        jTextFieldNomCompañia.setEditable(false);
        jTextFieldNomCompañia.setEnabled(false);
        jTextFieldNomCompañia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomCompañiaKeyTyped(evt);
            }
        });

        jLabelPiso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPiso.setText("Piso");

        jTextFieldNum.setEditable(false);
        jTextFieldNum.setEnabled(false);
        jTextFieldNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumKeyTyped(evt);
            }
        });

        jTextFieldTlf.setEditable(false);
        jTextFieldTlf.setEnabled(false);
        jTextFieldTlf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTlfKeyTyped(evt);
            }
        });

        jLabelNomOficina.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNomOficina.setText("Oficina");

        jLabelTlf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelTlf.setText("Telefono");

        jLabelDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDireccion.setText("Direccion");

        jLabelNomCompañia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNomCompañia.setText("Nombre Compañía");

        jTextFieldNomOficina.setEditable(false);
        jTextFieldNomOficina.setEnabled(false);
        jTextFieldNomOficina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomOficinaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Ofertas que casan para los Candidatos");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Si su jornada no es Completa seleccione la siguiente casilla");

        jTextFieldDedicacion.setEditable(false);
        jTextFieldDedicacion.setEnabled(false);
        jTextFieldDedicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDedicacionActionPerformed(evt);
            }
        });
        jTextFieldDedicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDedicacionKeyTyped(evt);
            }
        });

        jLabelDedicacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDedicacion.setText("Tiempo de Dedicación");

        jCheckBoxJornada.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBoxJornada.setText("Jornada Laboral Parcial");
        jCheckBoxJornada.setEnabled(false);

        jTextFieldSalMin.setEditable(false);
        jTextFieldSalMin.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Salario Máximo");

        jTextFieldSalMax.setEditable(false);
        jTextFieldSalMax.setEnabled(false);

        jTextFieldOcupaciones.setEditable(false);
        jTextFieldOcupaciones.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Salario Mínimo");

        jLabelSueldo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelSueldo.setText("Rango Salarial");

        jLabelOcupaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelOcupaciones.setText("Categorías de Empleo");

        jLabelFehcaCadu.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelFehcaCadu.setText("Fecha Caducidad");

        jSpinnerFechaCadu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jSpinnerFechaCadu.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(978303600000L), new java.util.Date(1924902000000L), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFechaCadu.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaCadu, "d/MM/yyyy"));
        jSpinnerFechaCadu.setEnabled(false);

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinnerFechaAper,"DD/MM/yyyy");
        jSpinnerFechaAper.setEditor(de);
        jSpinnerFechaAper.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jSpinnerFechaAper.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(978303600000L), new java.util.Date(1924902000000L), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFechaAper.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAper, "d/MM/yyyy"));
        jSpinnerFechaAper.setEnabled(false);

        jLabelFechaAper.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelFechaAper.setText("Fecha Apertura");

        VolverMenuP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        VolverMenuP.setForeground(new java.awt.Color(0, 102, 255));
        VolverMenuP.setText("ATRÁS");
        VolverMenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPActionPerformed(evt);
            }
        });

        jButtonAnt.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonAnt.setText("ANTERIOR");
        jButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntActionPerformed(evt);
            }
        });

        jButtonSig.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonSig.setText("SIGUIENTE");
        jButtonSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSigActionPerformed(evt);
            }
        });

        jButtonImprimir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonImprimir.setText("IMPRIMIR OFERTA");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabelTitulo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(264, 264, 264)
                                        .addComponent(jLabel1)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabelNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPiso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelLetra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelDireccion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelTlf)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelNomOficina)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldNomOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelNomCompañia)
                                            .addGap(56, 56, 56)
                                            .addComponent(jTextFieldNomCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabelLoca)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelCodPos))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabelClaves)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldClaves)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonAnt)
                                        .addGap(260, 260, 260)
                                        .addComponent(jButtonImprimir)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jCheckBoxJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelDedicacion)
                                                .addGap(25, 25, 25)
                                                .addComponent(jTextFieldDedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelSueldo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))
                                                .addGap(63, 63, 63)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldSalMin)
                                                    .addComponent(jTextFieldSalMax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelFechaAper, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelFehcaCadu)
                                                    .addComponent(jLabelOcupaciones))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSpinnerFechaAper)
                                                    .addComponent(jSpinnerFechaCadu)
                                                    .addComponent(jTextFieldOcupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(109, 109, 109))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonSig)
                                        .addGap(85, 85, 85))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VolverMenuP)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNomCompañia)
                                    .addComponent(jTextFieldNomCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNomOficina)
                                    .addComponent(jTextFieldNomOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTlf)
                                    .addComponent(jTextFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDireccion)
                                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNum)
                                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPiso)
                                    .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLetra)
                                    .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCodPos)
                                        .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelLoca))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelClaves)
                                    .addComponent(jTextFieldClaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelSueldo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldSalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldSalMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxJornada)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDedicacion)
                                    .addComponent(jTextFieldDedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelOcupaciones)
                                    .addComponent(jTextFieldOcupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFechaAper)
                                    .addComponent(jSpinnerFechaAper, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFehcaCadu)
                                    .addComponent(jSpinnerFechaCadu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnt)
                    .addComponent(jButtonSig)
                    .addComponent(jButtonImprimir))
                .addGap(32, 32, 32)
                .addComponent(VolverMenuP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodPosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodPosKeyTyped
    }//GEN-LAST:event_jTextFieldCodPosKeyTyped

    private void jTextFieldLetraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLetraKeyTyped
    }//GEN-LAST:event_jTextFieldLetraKeyTyped

    private void jTextFieldPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPisoKeyTyped
    }//GEN-LAST:event_jTextFieldPisoKeyTyped

    private void jTextFieldNomCompañiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomCompañiaKeyTyped
    }//GEN-LAST:event_jTextFieldNomCompañiaKeyTyped

    private void jTextFieldNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumKeyTyped
    }//GEN-LAST:event_jTextFieldNumKeyTyped

    private void jTextFieldTlfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTlfKeyTyped
    }//GEN-LAST:event_jTextFieldTlfKeyTyped

    private void jTextFieldNomOficinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomOficinaKeyTyped
    }//GEN-LAST:event_jTextFieldNomOficinaKeyTyped

    private void jTextFieldDedicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDedicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDedicacionActionPerformed

    private void jTextFieldDedicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDedicacionKeyTyped
    }//GEN-LAST:event_jTextFieldDedicacionKeyTyped

    private void jButtonAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntActionPerformed
        if (iterador.hayAnterior()) {
            of = (Oferta) iterador.anterior();
        }
        //Si hay candidatos podrá ir atrás y visualizar los datos en los campos correspondientes
        if (of != null) {
            verDatos(of);
        } else {
            JOptionPane.showMessageDialog(this, "No se encuentran más ofertas disponibles");
        }
    }//GEN-LAST:event_jButtonAntActionPerformed

    private void jButtonSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSigActionPerformed
        if (iterador.hayMas()) {//Recorremos el array con el iterator
            of = (Oferta) iterador.siguiente();
        }
        //Si hay candidatos
        if (of != null) {
            verDatos(of);
        } else {
            JOptionPane.showMessageDialog(this, "No hay ofertas disponibles");
        }
    }//GEN-LAST:event_jButtonSigActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        try {
            
            if (of != null) {//Si el objeto no es nulo presenta la ficha
                proxy.imprimir(of);
                JOptionPane.showMessageDialog(this, "Oferta disponible para el candidato " + "\nEmpresa" + of.getOficina().getNomCompañia() + "\nOficina Asociada" + of.getOficina().getNomOficina() + ".txt", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        UtilSistema.borrarOfertas();

    }//GEN-LAST:event_formWindowClosing

    private void VolverMenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPActionPerformed
        UtilSistema.guardarDatos();
        BusquedaOfertaParaCandidato ventana = new BusquedaOfertaParaCandidato();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuPActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton VolverMenuP;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonSig;
    private javax.swing.JCheckBox jCheckBoxJornada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClaves;
    private javax.swing.JLabel jLabelCodPos;
    private javax.swing.JLabel jLabelDedicacion;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFechaAper;
    private javax.swing.JLabel jLabelFehcaCadu;
    private javax.swing.JLabel jLabelLetra;
    private javax.swing.JLabel jLabelLoca;
    private javax.swing.JLabel jLabelNomCompañia;
    private javax.swing.JLabel jLabelNomOficina;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelOcupaciones;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTlf;
    private javax.swing.JSpinner jSpinnerFechaAper;
    private javax.swing.JSpinner jSpinnerFechaCadu;
    public static javax.swing.JTextField jTextFieldClaves;
    public static javax.swing.JTextField jTextFieldCodPos;
    private javax.swing.JTextField jTextFieldDedicacion;
    public static javax.swing.JTextField jTextFieldDireccion;
    public static javax.swing.JTextField jTextFieldLetra;
    public static javax.swing.JTextField jTextFieldLoca;
    private javax.swing.JTextField jTextFieldNomCompañia;
    public static javax.swing.JTextField jTextFieldNomOficina;
    public static javax.swing.JTextField jTextFieldNum;
    public static javax.swing.JTextField jTextFieldOcupaciones;
    public static javax.swing.JTextField jTextFieldPiso;
    public static javax.swing.JTextField jTextFieldSalMax;
    public static javax.swing.JTextField jTextFieldSalMin;
    public static javax.swing.JTextField jTextFieldTlf;
    // End of variables declaration//GEN-END:variables
}
