/**Práctica Final Patrones de Software 2015/2016
 * Agencia de Busqueda de Empleo
 *Alumnos: Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 * Clase RegistroCandidatos
 */
package AgenciaSwing;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Permite introducir los datos de los candidatos para registrarlos
 * @author Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 */
public class RegistroCandidatos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCandidatos
     */
    private FileInputStream fis;//donde almacenamos el flujo de datos que selecconamos en este caso una imagen
    private int longitudBytes;
//Creamos el modelo de la tabla
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Constructor
     */
    public RegistroCandidatos() {
        initComponents();
        this.setLocationRelativeTo(null);//Centramos la pantalla
        PanelFondo F = new PanelFondo(); //Creamos el objeto F de tipo PanelFondo
        this.add(F, BorderLayout.CENTER);
        this.pack();
        //Mostramos las columnas de la tabla
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("NIF");
        modelo.addColumn("Telefono");
        modelo.addColumn("Dirección");
        modelo.addColumn("Ocupaciones");
        modelo.addColumn("Sueldo");
        tablaCandidatos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelTitulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTlf = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldNIF = new javax.swing.JTextField();
        jTextFieldTlf = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jButtonBorrar = new javax.swing.JButton();
        VolverMenuP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSueldo = new javax.swing.JComboBox();
        jLabelNum = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jLabelLetra = new javax.swing.JLabel();
        jTextFieldLetra = new javax.swing.JTextField();
        jLabelLoca = new javax.swing.JLabel();
        jTextFieldLoca = new javax.swing.JTextField();
        jLabelCodPos = new javax.swing.JLabel();
        jTextFieldCodPos = new javax.swing.JTextField();
        lbFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelOcupaciones = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCandidatos = new javax.swing.JTable();
        Insertar = new javax.swing.JButton();
        jComboBoxOcupaciones = new javax.swing.JComboBox();
        jLabelDicapacidad = new javax.swing.JLabel();
        jComboBoxDiscapacidad = new javax.swing.JComboBox();

        jMenuItem1.setText("Enviar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de Empleo - Registro Candidato");

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelTitulo.setText("AGENCIA DE EMPLEO");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setAlignmentX(0.5F);
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e-Business.jpg"))); // NOI18N
        Logo.setText("jLabel5");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Regístrese aquí para enviar su CV de forma gratuita y para solicitar empleos por toda España.");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setText("Le deseamos lo mejor en su búsqueda.");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Información Personal");

        jLabelNombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelApellidos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelApellidos.setText("Apellidos");

        jLabelNIF.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNIF.setText("NIF");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabel9.setText("campo obligatorio");

        jLabelTlf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelTlf.setText("Telefono ");

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyTyped(evt);
            }
        });

        jTextFieldNIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNIFKeyTyped(evt);
            }
        });

        jTextFieldTlf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTlfKeyTyped(evt);
            }
        });

        jLabelDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDireccion.setText("Dirección");

        jButtonBorrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonBorrar.setForeground(new java.awt.Color(0, 102, 255));
        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        VolverMenuP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        VolverMenuP.setForeground(new java.awt.Color(0, 102, 255));
        VolverMenuP.setText("ATRÁS");
        VolverMenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Salario Neto Anual");

        jComboBoxSueldo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0-18000", "18000-30000", "30000 o más" }));

        jLabelNum.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNum.setText("Nº");

        jTextFieldNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumKeyTyped(evt);
            }
        });

        jLabelPiso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPiso.setText("Piso");

        jTextFieldPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPisoKeyTyped(evt);
            }
        });

        jLabelLetra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLetra.setText("Letra");

        jTextFieldLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLetraKeyTyped(evt);
            }
        });

        jLabelLoca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLoca.setText("Localidad");

        jLabelCodPos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelCodPos.setText("Código Postal");

        jTextFieldCodPos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodPosKeyTyped(evt);
            }
        });

        lbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/defaultlarge.gif"))); // NOI18N
        lbFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbFotoMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Información Laboral");

        jLabelOcupaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelOcupaciones.setText("Categorías de Empleo");

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabel6.setText("Pinche el icono para seleccionar una imagen");

        tablaCandidatos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tablaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCandidatos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(tablaCandidatos);

        Insertar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Insertar.setForeground(new java.awt.Color(0, 102, 255));
        Insertar.setText("INSERTAR");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        jComboBoxOcupaciones.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxOcupaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Administrativo", "Aereospacial", "Aeropuerto", "Agricultura", "Almacén", "Ambiente", "Arquitectura", "Automotor", "Aviación", "Bancos/operaciones bancarias", "Belleza/Cosmética", "Biotech", "Ciencia/Tecnología", "Comercialización", "Comprar", "Computación Gráfica/Animación", "Computadora/Computer", "Construcción", "Consultor/Consulta", "Contabilidad/Auditoría", "Control de Calidad", "Costes de la Edificación", "Cuidado de niños/Nanny", "Deportes", "Desarrollo de Software", "Diseño Web/Desing", "Diseño/Multimedia ", "Distribución ", "Doctor en Medicina ", "Ecología/Conservación ", "Educación ", "Electrónica ", "Energía ", "Enfermería/Enfermera ", "Enseñanza/Profesor ", "Entertainment ", "Especialista/Experto ", "Explotación Minera ", "Fabricación ", "Farmacéutico ", "Finanzas ", "Geociencia ", "Gerencia/Dirección ", "Gobierno ", "Hospitalidad ", "Hotel/Hoteles ", "Idiomas/Multilingüe ", "Impuesto ", "Independiente ", "Industria Del Gas ", "Industria del Petróleo ", "Industrial ", "Ingeniería/de Ingeniero ", "Inmobiliaria/Agente inmobiliario ", "Instalación ", "Investigación/Desarrollo ", "Juego ", "Leyes/Legales ", "Logística ", "Mantenimiento ", "Mecánicos ", "Media/Artes audiovisuales ", "Moda ", "Non Profit ", "Peluquería/Peluquero ", "Producción ", "Profesor de español/profesora ", "Programador ", "Práctica/Entrenamiento ", "Publicar ", "Publicidad ", "Reclutamiento/Seleccion ", "Restaurant/Gastronomía ", "Secretaria ", "Sector Público ", "Seguridad ", "Seguro ", "Servicio Al Cliente ", "Servicios Médicos ", "Soporte Tecnico/Helpdesk ", "Tecnología De Información ", "Telecomunicaciones ", "Telesales/Telemarketing ", "Televisión/Radio/Difusión ", "Trabajador Cualificado ", "Trabajador Social ", "Traducción ", "Transformación De los Alimentos ", "Transporte ", "Turismo ", "Técnico de Laboratorio ", "Venta al por menor/mayor ", "Ventas ", "Verano ", "Viajes/Agente de Viajes ", "Voluntario ", "Web/Internet ", "al Aire libre/Aventura ", "de Odontología/Dentista odontologo " }));

        jLabelDicapacidad.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDicapacidad.setText("Discapacidad");

        jComboBoxDiscapacidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "No Discapacitado", "Discapacitad Parcial", "Discapacidad>50" }));
        jComboBoxDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiscapacidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDireccion)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelLoca)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabelCodPos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(323, 323, 323))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VolverMenuP)
                                .addGap(519, 519, 519)
                                .addComponent(Insertar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelPiso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelLetra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabelApellidos)
                                    .addComponent(jLabelNIF)
                                    .addComponent(jLabelTlf)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(337, 337, 337)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jLabelOcupaciones)
                                                            .addComponent(jLabelDicapacidad))
                                                        .addGap(56, 56, 56)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jComboBoxSueldo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jComboBoxOcupaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBoxDiscapacidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabelTitulo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jComboBoxSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelNombre)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidos)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOcupaciones)
                            .addComponent(jComboBoxOcupaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNIF)
                            .addComponent(jLabelDicapacidad)
                            .addComponent(jComboBoxDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTlf)
                            .addComponent(jTextFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDireccion)
                            .addComponent(jLabelNum)
                            .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPiso)
                            .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLetra)
                            .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLoca)
                            .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodPos)
                            .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VolverMenuP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBorrar)
                            .addComponent(Insertar))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        // Impedimos que el usuario pueda introducir en el campo de nombre dígitos
        /*Para ello lo que hacemos con el evento evt.getKeyChar es que cuendo el usuario pulse un dígito no lo reconozca y por tanto no se escriba
         Por ello cada dígito que presione el usuario, se almacena en la variable evt  */
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldTlfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTlfKeyTyped
        // Prevenimos que el usuario introduzca letras en el campo de Telefono
/*Para ello lo que hacemos con el evento evt.getKeyChar es que cuendo el usuario pulse una letra no la reconozca y por tanto no se escriba
         Por ello cada caracter que presione el usuario se almacena en la variable evt  */
        //atributo que limita el número de caracteres a introducir en el campo del telefono
        int limite = 9;
        if (jTextFieldTlf.getText().length() == limite) {
            evt.consume();//Una vez se halla introducido 9 dígitos el resto serán capturados y almacenados en la variable evt
        }
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTlfKeyTyped

    private void jTextFieldApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyTyped
        // Impedimos que el usuario pueda introducir dígitos en el campo Apellidos
        /*Para ello lo que hacemos con el evento evt.getKeyChar es que cuendo el usuario pulse un dígito no lo reconozca y por tanto no se escriba
         Por ello cada dígito que presione el usuario, se almacena en la variable evt  */
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldApellidosKeyTyped

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // El usuario podrá eliminar los campos escritos
        jTextFieldNombre.setText(" ");
        jTextFieldApellidos.setText(" ");
        jTextFieldNIF.setText(" ");
        jTextFieldTlf.setText(" ");
        jTextFieldDireccion.setText(" ");
        jTextFieldNum.setText(" ");
        jTextFieldPiso.setText(" ");
        jTextFieldCodPos.setText(" ");
        jTextFieldLetra.setText(" ");
        jTextFieldLoca.setText(" ");
        jComboBoxSueldo.setSelectedIndex(0);
        jComboBoxOcupaciones.setSelectedIndex(0);

    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void VolverMenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPActionPerformed

        RegistroEC ventana = new RegistroEC();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuPActionPerformed

    private void jTextFieldNIFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNIFKeyTyped
        // Limita el número de carácteres a introducir por el usuario para el DNI
        int limite = 9;
        if (jTextFieldNIF.getText().length() == limite) {
            evt.consume();//Una vez se halla introducido 9 caracteres el resto serán capturados y almacenados en la variable evt
        }
    }//GEN-LAST:event_jTextFieldNIFKeyTyped

    private void jTextFieldNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumKeyTyped
        //Prevenimos que el usuario introduzca letras en el campo del número de edificio
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumKeyTyped

    private void jTextFieldPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPisoKeyTyped
        //Prevenimos que el usuario introduzca letras en el campo del piso
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPisoKeyTyped

    private void jTextFieldLetraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLetraKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLetraKeyTyped

    private void jTextFieldCodPosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodPosKeyTyped
        // TODO add your handling code here:
        int limite = 5;
        if (jTextFieldCodPos.getText().length() == limite) {
            evt.consume();//Una vez se halla introducido 5 dígitos el resto serán capturados y almacenados en la variable evt
        }
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodPosKeyTyped

    private void lbFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFotoMouseClicked
        // Cada vez que se haga click en el JLabel aparecerá un selector de archivos
        JFileChooser se = new JFileChooser();
        se.setFileSelectionMode(JFileChooser.FILES_ONLY);    //Solo deja seleccionar archivos no carpetas   
        int estado = se.showOpenDialog(null);
        if (estado == JFileChooser.APPROVE_OPTION)//si selecciona el archivo y dio a aceptar
        {
            try {
                //Con esto lo que hacemos es grabar la imagen de la base de datos
                fis = new FileInputStream(se.getSelectedFile());
                //Necesitamos saber la longitud de bytes que tiene el archivo
                this.longitudBytes = (int) se.getSelectedFile().length();//Nos devolvía un long asique lo pasamos a un entero simple(int)

                Image icono = ImageIO.read(se.getSelectedFile()).getScaledInstance(lbFoto.getWidth(), lbFoto.getHeight(), Image.SCALE_DEFAULT);//Con esto hacemos que la imagen escogida se adapte al label
                lbFoto.setIcon(new ImageIcon(icono));
                lbFoto.updateUI();

            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_lbFotoMouseClicked

    /*
     * Los datos que el usuario a escrito se introducirán en la tabla para visualizarlos
     */
    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        if (this.jTextFieldNombre.getText().isEmpty() //si los campos estan vacíos avisa de ser obligatorio
                || this.jTextFieldApellidos.getText().isEmpty()
                || this.jTextFieldNIF.getText().isEmpty()
                || this.jTextFieldTlf.getText().isEmpty()
                || this.jTextFieldDireccion.getText().isEmpty()
                || this.jTextFieldLetra.getText().isEmpty()
                || this.jTextFieldLetra.getText().isEmpty()
                || this.jTextFieldPiso.getText().isEmpty()
                || this.jTextFieldNum.getText().isEmpty()
                || this.jTextFieldLoca.getText().isEmpty()
                || this.jTextFieldCodPos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son "
                    + "obligatorios");
            return;
        }
        String[] datos = new String[7];
        datos[0] = jTextFieldNombre.getText();
        datos[1] = jTextFieldApellidos.getText();
        datos[2] = jTextFieldNIF.getText();
        datos[3] = jTextFieldTlf.getText();
        datos[4] = jTextFieldDireccion.getText();
        datos[5] = jComboBoxOcupaciones.getSelectedItem().toString();
        datos[6] = jComboBoxSueldo.getSelectedItem().toString();
        //agregamos filas a la tabla
        modelo.addRow(datos);
    }//GEN-LAST:event_InsertarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        DefaultTableModel model = (DefaultTableModel) GestionCandidatos.jTableDatos.getModel();
        //capturamos la fila que hemos seleccionado
        int filaSele = tablaCandidatos.getSelectedRow();
        // capturamos los datos de la columna, con un vector para trabajar con el Model
        String[] registros = new String[7];
        /*colocamos en cada posición qué obtiene el vector
         * Esto es: lo que se envia de la fila y de la columna
         * usamos .toString
         */
        registros[0] = tablaCandidatos.getValueAt(filaSele, 0).toString();
        registros[1] = tablaCandidatos.getValueAt(filaSele, 1).toString();
        registros[2] = tablaCandidatos.getValueAt(filaSele, 2).toString();
        registros[3] = tablaCandidatos.getValueAt(filaSele, 3).toString();
        registros[4] = tablaCandidatos.getValueAt(filaSele, 4).toString();
        registros[5] = tablaCandidatos.getValueAt(filaSele, 5).toString();
        registros[6] = tablaCandidatos.getValueAt(filaSele, 6).toString();
        model.addRow(registros);
        GestionCandidatos.jTableDatos.setModel(model);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBoxDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiscapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDiscapacidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidatos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCandidatos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertar;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton VolverMenuP;
    private javax.swing.JButton jButtonBorrar;
    public static javax.swing.JComboBox jComboBoxDiscapacidad;
    public static javax.swing.JComboBox jComboBoxOcupaciones;
    public static javax.swing.JComboBox jComboBoxSueldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCodPos;
    private javax.swing.JLabel jLabelDicapacidad;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelLetra;
    private javax.swing.JLabel jLabelLoca;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelOcupaciones;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTlf;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldApellidos;
    public static javax.swing.JTextField jTextFieldCodPos;
    public static javax.swing.JTextField jTextFieldDireccion;
    public static javax.swing.JTextField jTextFieldLetra;
    public static javax.swing.JTextField jTextFieldLoca;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldNombre;
    public static javax.swing.JTextField jTextFieldNum;
    public static javax.swing.JTextField jTextFieldPiso;
    private javax.swing.JTextField jTextFieldTlf;
    private javax.swing.JLabel lbFoto;
    public static javax.swing.JTable tablaCandidatos;
    // End of variables declaration//GEN-END:variables
}
