/**Práctica Final Patrones de Software 2015/2016
 * Agencia de Busqueda de Empleo
 *Alumnos: Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 * Clase RegistroContratante
 */
package AgenciaSwing;

import java.awt.BorderLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 * Permite introducir los datos de las empresas para registrarlas
 * @author Cristina Sáez Ortega - Claudia Rodriguez Peinado - Jose Andrés Guerra Bermejo
 */
public class RegistroContratante extends javax.swing.JFrame {

    /**
     * Creates new form RegistroContratante
     */
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Constructor
     */
    public RegistroContratante() {
        initComponents();
        this.setLocationRelativeTo(null);//Centramos la pantalla
        PanelFondo F = new PanelFondo(); //Creamos el objeto F de tipo PanelFondo
        this.add(F, BorderLayout.CENTER);
        this.pack();

        //Creamos el Spinner de Fecha de Apertura de la Oferta

        Calendar cal = Calendar.getInstance();
        Date datInicial = cal.getTime();
        cal.add(Calendar.YEAR, -50);//la fecha que utilizaré como primera
        Date datPrimera = cal.getTime();
        cal.add(Calendar.YEAR, 100);//le sumamos 100 dias( 50 años para atrás y 50 años para alante)
        Date datUltima = cal.getTime();
        //Creamos el modelo para el Spinner

        jSpinnerFechaAper.setModel(new SpinnerDateModel(
                datInicial, datPrimera, datUltima, Calendar.DAY_OF_MONTH));
        jSpinnerFechaAper.setEditor(new JSpinner.DateEditor(jSpinnerFechaAper, "d/MM/yyyy"));//Le pasamos el Spinner sobre el que va a actuar y la máscara
        jSpinnerFechaCadu.setModel(new SpinnerDateModel(
                datInicial, datPrimera, datUltima, Calendar.DAY_OF_MONTH));
        jSpinnerFechaCadu.setEditor(new JSpinner.DateEditor(jSpinnerFechaCadu, "d/MM/yyyy"));//Le pasamos el Spinner sobre el que va a actuar y la máscara

        //Creamos las columnas de la tabla
        modelo.addColumn("Compañia");
        modelo.addColumn("Oficina");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Ocupación");
        modelo.addColumn("Sueldos");
        modelo.addColumn("Jornada");
        jTableContratante.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNomCompañia = new javax.swing.JLabel();
        jTextFieldNomCompañia = new javax.swing.JTextField();
        jLabelFechaAper = new javax.swing.JLabel();
        jLabelFehcaCadu = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.DATE);
        jSpinnerFechaAper = new javax.swing.JSpinner(sm);
        Date dateC = new Date();
        SpinnerDateModel ca =
        new SpinnerDateModel(dateC, null, null, Calendar.DATE);
        jSpinnerFechaAper = new javax.swing.JSpinner(ca);
        JSpinner.DateEditor cadu = new JSpinner.DateEditor(jSpinnerFechaAper,"DD/MM/yyyy");
        jSpinnerFechaAper.setEditor(cadu);
        jSpinnerFechaCadu = new javax.swing.JSpinner(ca);
        VolverMenuP = new javax.swing.JButton();
        jLabelSueldo = new javax.swing.JLabel();
        jComboBoxSueldo = new javax.swing.JComboBox();
        jLabelHorario = new javax.swing.JLabel();
        jComboBoxJornada = new javax.swing.JComboBox();
        jButtonBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelOcupaciones = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelLoca = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelNum = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jLabelLetra = new javax.swing.JLabel();
        jTextFieldLetra = new javax.swing.JTextField();
        jTextFieldLoca = new javax.swing.JTextField();
        jLabelCodPos = new javax.swing.JLabel();
        jTextFieldCodPos = new javax.swing.JTextField();
        jLabelNomOficina = new javax.swing.JLabel();
        jTextFieldNomOficina = new javax.swing.JTextField();
        jComboBoxOcupa = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContratante = new javax.swing.JTable();
        Insertar = new javax.swing.JButton();
        jLabelTlf = new javax.swing.JLabel();
        jTextFieldTlf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de Empleo - Registro Empresa");

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelTitulo.setText("AGENCIA DE EMPLEO");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setAlignmentX(0.5F);
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e-Business.jpg"))); // NOI18N
        Logo.setText("jLabel5");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Anuncio de puesto de trabajo gratis y publicidad de pago disponible.");

        jLabelNomCompañia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNomCompañia.setText("Compañía");

        jLabelFechaAper.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelFechaAper.setText("Fecha Apertura");

        jLabelFehcaCadu.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelFehcaCadu.setText("Fecha Caducidad");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinnerFechaAper,"DD/MM/yyyy");
        jSpinnerFechaAper.setEditor(de);
        jSpinnerFechaAper.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jSpinnerFechaAper.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(978303600000L), new java.util.Date(1924902000000L), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFechaAper.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAper, "d/MM/yyyy"));

        jSpinnerFechaCadu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jSpinnerFechaCadu.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(978303600000L), new java.util.Date(1924902000000L), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFechaCadu.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaCadu, "d/MM/yyyy"));

        VolverMenuP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        VolverMenuP.setForeground(new java.awt.Color(0, 102, 255));
        VolverMenuP.setText("ATRÁS");
        VolverMenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPActionPerformed(evt);
            }
        });

        jLabelSueldo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelSueldo.setText("Rango Salarial");

        jComboBoxSueldo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0-18000", "18000-30000", "30000 o más" }));

        jLabelHorario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelHorario.setText("Jornada Laboral");

        jComboBoxJornada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Jornada Completa", "Jornada Parcial" }));

        jButtonBorrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonBorrar.setForeground(new java.awt.Color(0, 102, 255));
        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.setToolTipText("");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Información del Contratante");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Información de la Oferta");

        jLabelOcupaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelOcupaciones.setText("Categorías de Empleo");

        jLabel9.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabel9.setText("campo obligatorio");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        jLabelDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelDireccion.setText("Dirección");

        jLabelLoca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLoca.setText("Localidad");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");

        jLabelNum.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNum.setText("Nº");

        jTextFieldNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumKeyTyped(evt);
            }
        });

        jLabelPiso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPiso.setText("Piso");

        jTextFieldPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPisoKeyTyped(evt);
            }
        });

        jLabelLetra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelLetra.setText("Letra");

        jTextFieldLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLetraKeyTyped(evt);
            }
        });

        jLabelCodPos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelCodPos.setText("Código Postal");

        jTextFieldCodPos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodPosKeyTyped(evt);
            }
        });

        jLabelNomOficina.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNomOficina.setText("Oficina");

        jComboBoxOcupa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Administrativo", "Aereospacial", "Aeropuerto", "Agricultura", "Almacén", "Ambiente", "Arquitectura", "Automotor", "Aviación", "Bancos/operaciones bancarias", "Belleza/Cosmética", "Biotech", "Ciencia/Tecnología", "Comercialización", "Comprar", "Computación Gráfica/Animación", "Computadora/Computer", "Construcción", "Consultor/Consulta", "Contabilidad/Auditoría", "Control de Calidad", "Costes de la Edificación", "Cuidado de niños/Nanny", "Deportes", "Desarrollo de Software", "Diseño Web/Desing", "Diseño/Multimedia ", "Distribución ", "Doctor en Medicina ", "Ecología/Conservación ", "Educación ", "Electrónica ", "Energía ", "Enfermería/Enfermera ", "Enseñanza/Profesor ", "Entertainment ", "Especialista/Experto ", "Explotación Minera ", "Fabricación ", "Farmacéutico ", "Finanzas ", "Geociencia ", "Gerencia/Dirección ", "Gobierno ", "Hospitalidad ", "Hotel/Hoteles ", "Idiomas/Multilingüe ", "Impuesto ", "Independiente ", "Industria Del Gas ", "Industria del Petróleo ", "Industrial ", "Ingeniería/de Ingeniero ", "Inmobiliaria/Agente inmobiliario ", "Instalación ", "Investigación/Desarrollo ", "Juego ", "Leyes/Legales ", "Logística ", "Mantenimiento ", "Mecánicos ", "Media/Artes audiovisuales ", "Moda ", "Non Profit ", "Peluquería/Peluquero ", "Producción ", "Profesor de español/profesora ", "Programador ", "Práctica/Entrenamiento ", "Publicar ", "Publicidad ", "Reclutamiento/Seleccion ", "Restaurant/Gastronomía ", "Secretaria ", "Sector Público ", "Seguridad ", "Seguro ", "Servicio Al Cliente ", "Servicios Médicos ", "Soporte Tecnico/Helpdesk ", "Tecnología De Información ", "Telecomunicaciones ", "Telesales/Telemarketing ", "Televisión/Radio/Difusión ", "Trabajador Cualificado ", "Trabajador Social ", "Traducción ", "Transformación De los Alimentos ", "Transporte ", "Turismo ", "Técnico de Laboratorio ", "Venta al por menor/mayor ", "Ventas ", "Verano ", "Viajes/Agente de Viajes ", "Voluntario ", "Web/Internet ", "al Aire libre/Aventura ", "de Odontología/Dentista odontologo " }));

        jTableContratante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableContratante);

        Insertar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Insertar.setForeground(new java.awt.Color(0, 102, 255));
        Insertar.setText("INSERTAR");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        jLabelTlf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelTlf.setText("Telefono");

        jTextFieldTlf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTlfKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabelTitulo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNomOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNomCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(251, 251, 251)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelOcupaciones)
                                                    .addComponent(jLabelFechaAper, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelFehcaCadu)
                                                    .addComponent(jLabelSueldo)
                                                    .addComponent(jLabelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSpinnerFechaCadu)
                                                    .addComponent(jSpinnerFechaAper)
                                                    .addComponent(jComboBoxSueldo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboBoxJornada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboBoxOcupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelNomCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomOficina)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabelNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelPiso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelLetra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldTlf)
                                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                            .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLoca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCodPos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTlf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VolverMenuP)
                        .addGap(341, 341, 341)
                        .addComponent(Insertar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrar)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomCompañia)
                            .addComponent(jTextFieldNomCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomOficina)
                            .addComponent(jTextFieldNomOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTlf)
                            .addComponent(jTextFieldTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDireccion)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNum)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPiso)
                            .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLetra)
                            .addComponent(jTextFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerFechaAper, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerFechaCadu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFehcaCadu))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSueldo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelHorario))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxOcupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelOcupaciones)))
                            .addComponent(jLabelFechaAper))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoca)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldLoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodPos)
                    .addComponent(jTextFieldCodPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverMenuP)
                    .addComponent(Insertar)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPActionPerformed

        RegistroEC ventana = new RegistroEC();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuPActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // El usuario podrá eliminar los campos escritos
        jTextFieldNomCompañia.setText(" ");
        jTextFieldNomOficina.setText(" ");
        jTextFieldTlf.setText(" ");
        jTextFieldDireccion.setText(" ");
        jTextFieldNum.setText(" ");
        jTextFieldPiso.setText(" ");
        jTextFieldCodPos.setText(" ");
        jTextFieldLetra.setText(" ");
        jTextFieldLoca.setText(" ");
        jComboBoxJornada.setSelectedItem("");
        jComboBoxOcupa.setSelectedItem(" ");
        jComboBoxSueldo.setSelectedItem("");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumKeyTyped
        //Prevenimos que el usuario introduzca letras en el campo del número de edificio
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumKeyTyped

    private void jTextFieldPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPisoKeyTyped
        //Prevenimos que el usuario introduzca letras en el campo del piso
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPisoKeyTyped

    private void jTextFieldLetraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLetraKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLetraKeyTyped

    private void jTextFieldCodPosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodPosKeyTyped
        // TODO add your handling code here:
        int limite = 5;
        if (jTextFieldCodPos.getText().length() == limite) {
            evt.consume();//Una vez se halla introducido 5 dígitos el resto serán capturados y almacenados en la variable evt
        }
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodPosKeyTyped

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        if (this.jTextFieldNomCompañia.getText().isEmpty() //si los campos estan vacíos avisa de ser obligatorio
                || this.jTextFieldNomOficina.getText().isEmpty()
                || this.jTextFieldTlf.getText().isEmpty()
                || this.jTextFieldDireccion.getText().isEmpty()
                || this.jTextFieldLetra.getText().isEmpty()
                || this.jTextFieldLetra.getText().isEmpty()
                || this.jTextFieldPiso.getText().isEmpty()
                || this.jTextFieldNum.getText().isEmpty()
                || this.jTextFieldLoca.getText().isEmpty()
                || this.jTextFieldCodPos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son "
                    + "obligatorios, excepto la foto");
            return;
        }
        String[] datos = new String[7];
        datos[0] = jTextFieldNomCompañia.getText();
        datos[1] = jTextFieldNomOficina.getText();
        datos[2] = jTextFieldTlf.getText();
        datos[3] = jTextFieldDireccion.getText();
        datos[4] = jComboBoxOcupa.getSelectedItem().toString();
        datos[5] = jComboBoxSueldo.getSelectedItem().toString();
        datos[6] = jComboBoxJornada.getSelectedItem().toString();

        //agregamos filas a la tabla
        modelo.addRow(datos);
    }//GEN-LAST:event_InsertarActionPerformed

    private void jTextFieldTlfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTlfKeyTyped
        // Prevenimos que el usuario introduzca letras en el campo de Telefono
/*Para ello lo que hacemos con el evento evt.getKeyChar es que cuendo el usuario pulse una letra no la reconozca y por tanto no se escriba
         Por ello cada caracter que presione el usuario se almacena en la variable evt  */
        //atributo que limita el número de caracteres a introducir en el campo del telefono
        int limite = 9;
        if (jTextFieldTlf.getText().length() == limite) {
            evt.consume();//Una vez se halla introducido 9 dígitos el resto serán capturados y almacenados en la variable evt
        }
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {// si el caracter no esta entre 0 y 9 lo desechamos(evt.consume)
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTlfKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroContratante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroContratante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroContratante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroContratante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroContratante().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertar;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton VolverMenuP;
    private javax.swing.JButton jButtonBorrar;
    public static javax.swing.JComboBox jComboBoxJornada;
    public static javax.swing.JComboBox jComboBoxOcupa;
    public static javax.swing.JComboBox jComboBoxSueldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodPos;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFechaAper;
    private javax.swing.JLabel jLabelFehcaCadu;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelLetra;
    private javax.swing.JLabel jLabelLoca;
    private javax.swing.JLabel jLabelNomCompañia;
    private javax.swing.JLabel jLabelNomOficina;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelOcupaciones;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTlf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerFechaAper;
    private javax.swing.JSpinner jSpinnerFechaCadu;
    public static javax.swing.JTable jTableContratante;
    private javax.swing.JTextField jTextFieldCodPos;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldLetra;
    private javax.swing.JTextField jTextFieldLoca;
    private javax.swing.JTextField jTextFieldNomCompañia;
    private javax.swing.JTextField jTextFieldNomOficina;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldPiso;
    public static javax.swing.JTextField jTextFieldTlf;
    // End of variables declaration//GEN-END:variables
}
