package bibliopatrones;

import DecoratorArray_y_Marker.ConjuntoSocios;
import FactoryMethod_Strategy.Publicacion;
import DecoratorArray_y_Marker.LibreriaPublicaciones;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author doverride
 */
public class IzMostrarPublicDialog extends javax.swing.JDialog {

    LibreriaPublicaciones publicaciones;
    ConjuntoSocios socios;
    java.awt.Frame parent;
    /**
     * Creates new form IzMostrarPublicDialog
     */
    public IzMostrarPublicDialog(java.awt.Frame parent, boolean modal,LibreriaPublicaciones publicaciones, ConjuntoSocios socios) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.publicaciones = publicaciones;
        this.pintaPublicacion(publicaciones.primeraPubli());
        this.socios = socios;
        this.setVisible(true);
    }

    public LibreriaPublicaciones getPublicaciones(){
        return publicaciones;
    }
    
    private void avanzar(){
        this.pintaPublicacion(publicaciones.nextPubli());
        
    }
    private void pintaPublicacion(Publicacion publi){
        
        this.codigoLabel.setText(publi.getCodigo());
        this.isbnLabel.setText(publi.getISBN());
        this.tituloLabel.setText(publi.getTitulo());
        this.autorLabel.setText(publi.getAutores());
        if (publi.estaPrestada()){
            this.reservadoLabel.setText("No disponible");
        }else{
            this.reservadoLabel.setText("Disponible");
        }
    
        String tipo = publi.getTipo();
        switch(tipo){
            case "Libro":
                this.tipoPubliLabel.setText("LIBRO");
                this.param1Label.setText("Editorial");
                this.param2Label.setText("Contenido");
                this.param3Label.setText("Edicion");
                break;
            case "Revista":
                this.tipoPubliLabel.setText("REVISTA");
                this.param1Label.setText("Periodicidad");
                this.param2Label.setText("Volumen");
                this.param3Label.setText("NºPubli");
                break;
            default:
                this.tipoPubliLabel.setText("TESIS");
                this.param1Label.setText("Tribunal");
                this.param2Label.setText("Departamento");
                this.param3Label.setText("Calificación");
                break;
        }
                this.cParam1Label.setText(publi.getParam1());
                this.cParam2Label.setText(publi.getParam2());
                this.cParam3Label.setText(publi.getParam3());

    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        param1Label = new javax.swing.JLabel();
        param2Label = new javax.swing.JLabel();
        param3Label = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        autorLabel = new javax.swing.JLabel();
        cParam1Label = new javax.swing.JLabel();
        cParam3Label = new javax.swing.JLabel();
        cParam2Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        reservadoLabel = new javax.swing.JLabel();
        tipoPubliLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Codigo");

        jLabel6.setText("Titulo");

        jLabel7.setText("ISBN");

        jLabel8.setText("Autor");

        param1Label.setText("jLabel9");

        param2Label.setText("jLabel10");

        param3Label.setText("jLabel11");

        codigoLabel.setText("jLabel12");

        isbnLabel.setText("jLabel13");

        tituloLabel.setText("jLabel14");

        autorLabel.setText("jLabel15");

        cParam1Label.setText("jLabel16");

        cParam3Label.setText("jLabel17");

        cParam2Label.setText("jLabel18");

        jButton1.setText("Prestar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        reservadoLabel.setText("Disponible");

        tipoPubliLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(param1Label)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addComponent(param3Label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel)
                            .addComponent(tituloLabel)
                            .addComponent(cParam1Label)
                            .addComponent(cParam3Label))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(reservadoLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(param2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(cParam2Label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(autorLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isbnLabel)))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoPubliLabel)
                        .addGap(138, 138, 138)
                        .addComponent(jButton3)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(tipoPubliLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(codigoLabel)
                    .addComponent(isbnLabel))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(tituloLabel)
                    .addComponent(autorLabel))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(param1Label)
                    .addComponent(cParam1Label)
                    .addComponent(param2Label)
                    .addComponent(cParam2Label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(param3Label)
                            .addComponent(cParam3Label))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(reservadoLabel)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.setVisible(false);
        IzCrearPrestamoDialog creaPres = new IzCrearPrestamoDialog(parent,rootPaneCheckingEnabled, socios,publicaciones.publicacionActual(),publicaciones);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.avanzar();
    }//GEN-LAST:event_jButton3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorLabel;
    private javax.swing.JLabel cParam1Label;
    private javax.swing.JLabel cParam2Label;
    private javax.swing.JLabel cParam3Label;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel param1Label;
    private javax.swing.JLabel param2Label;
    private javax.swing.JLabel param3Label;
    private javax.swing.JLabel reservadoLabel;
    private javax.swing.JLabel tipoPubliLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
