/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliopatrones;

import Command.CommandInterfaz;
import Command.CommandPrestamoIntz;
import Decorator_Iterator.ConjuntoSocios;
import Decorator_Iterator.LibreriaPublicaciones;
import Facade.FacadeImpresoraBasica;
import FactoryMethod_Strategy.Publicacion;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author doverride
 */
public class IzCrearPrestamoDialog extends javax.swing.JDialog {

    /**
     * Creates new form IzCrearPrestamoDialog
     */

    ConjuntoSocios socios;
    Publicacion publicacion;
    LibreriaPublicaciones lPubli;
    FacadeImpresoraBasica impresora;
    CommandInterfaz miInterfaz;
    
    public IzCrearPrestamoDialog(java.awt.Frame parent, boolean modal, ConjuntoSocios socios, Publicacion publicacion, LibreriaPublicaciones p) {
        super(parent, modal);
        initComponents();
        this.miInterfaz = new CommandPrestamoIntz(this);
        this.lPubli = p;
        this.socios = socios;
        this.publicacion = publicacion;
        this.miInterfaz.executeUno();
   
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dniLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dniLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        dniLabel.setForeground(new java.awt.Color(0, 153, 51));
        dniLabel.setText("DNI:");
        getContentPane().add(dniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 51));
        jButton4.setText("ATRAS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 235, -1, -1));
        getContentPane().add(TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("¿QUÉ DESEA REALIZAR?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 19, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 153, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Elija una opcion-", "REALIZAR PRESTAMO", "DEVOLVER PRESTAMO", "CONSULTAR PRESTAMOS" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 69, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("PRESTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 235, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 204));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 134, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaslibros1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int opcion = this.jComboBox1.getSelectedIndex();
        
        switch(opcion){
            
        case 0:
             break;
            
        case 1:
//            this.jButton1.setVisible(true);
//            this.jButton1.setText("PRESTAR");
//            this.dniLabel.setVisible(true);
//            this.TextField.setVisible(true);
//            this.jTextArea1.setVisible(false);
            miInterfaz.executeUno();
            
                break;
        case 2:
        
//            this.jButton1.setVisible(true);
//            this.jButton1.setText("DEVOLVER");
//            this.dniLabel.setVisible(true);
//            this.TextField.setVisible(true);
//            this.jTextArea1.setVisible(false);
            miInterfaz.executeDos();
            break;
        default:
//            this.jButton1.setVisible(true);
//            this.jButton1.setText("CONSULTAR");
//            this.dniLabel.setVisible(true);
//            this.TextField.setVisible(true);
//            this.jTextArea1.setVisible(true);
//            jTextArea1.setText("");
            miInterfaz.executeTres();
            break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //if (jButton1.action("PRESTAR")){
        String dni = this.TextField.getText();
        int opcion = this.jComboBox1.getSelectedIndex();
        int imprime ;
        
        switch(opcion){
            
        case 0: //nada
          
             break;
            
        case 1: //prestar
            if (socios.estaSocio(dni)){
            if (publicacion.estaPrestada()){
                publicacion.adscribirNotifSocio(socios.getSocios().get(dni));
                JOptionPane.showMessageDialog(this, "ERROR: La publicacion "+publicacion.getCodigo()+" no se encuentra disponible");
            }
            else
            {
               
                this.publicacion.prestar(dni);
                JOptionPane.showMessageDialog(this, "Publicacion prestada correctamente: Fecha maxima devolucion: "+publicacion.getPrestamo().getFechaFinPrestamo());}
                String defPrest = "Prestamo realizado al socio :"+dni+" Publicacion: "+publicacion.getISBN()+" Fecha máxima de devolución"+publicacion.getPrestamo().getFechaFinPrestamo();
                this.impresora = new FacadeImpresoraBasica(defPrest, 1);
                
                imprime = JOptionPane.showConfirmDialog(rootPane,"¿Desea imprimir el ticket?", "ImpresoraBasica", opcion);
                if(imprime == 0) impresora.imprimir();
              
            }else{
                    JOptionPane.showMessageDialog(this, "ERROR: El usuario no se encuentra registrado");
            }
            
            break;
        case 2: //devolver
            if (publicacion.estaPrestada()){
                publicacion.devolver(this);
            }else if (!socios.estaSocio(dni)){
                    JOptionPane.showMessageDialog(this, "ERROR: El usuario no se encuentra registrado");   
            }
            else{
                JOptionPane.showMessageDialog(this, "ERROR: Usuario "+dni+" no tiene publicaciones prestadas");
            }
            break;
        default: //Consultar
            if (socios.estaSocio(dni)){
                jTextArea1.setText(lPubli.getReservasde(dni));
            }
            else 
            {
                JOptionPane.showMessageDialog(this, "ERROR: El usuario no se encuentra registrado");
            }
            
            break;
        }      
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */

    public JTextField getTextField() {
        return TextField;
    }

    public JLabel getDniLabel() {
        return dniLabel;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
