/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliopatrones;

import Decorator_Iterator.ConjuntoSocios;
import Observer.Socio;
import javax.swing.JOptionPane;

/**
 *
 * @author doverride
 */
public class IzCreaSocioDialog extends javax.swing.JDialog {
     Socio socio;
     ConjuntoSocios  s;
    /**
     * Creates new form IzCreaUsuarioDialog
     */
    public IzCreaSocioDialog(java.awt.Frame parent, boolean modal,ConjuntoSocios s) {
        super(parent, modal);
        initComponents();
        this.s = s;
        this.setVisible(true);
        
    }

    public Socio getNuevoSocio(){
        return this.socio;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dnijTextField = new javax.swing.JTextField();
        nombrejTextField = new javax.swing.JTextField();
        contraseniajTextField = new javax.swing.JTextField();
        aniadirSociojButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("DNI:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 80, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Categoria:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));
        getContentPane().add(dnijTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, -1));

        nombrejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrejTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nombrejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 80, -1));
        getContentPane().add(contraseniajTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 81, -1));

        aniadirSociojButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        aniadirSociojButton.setForeground(new java.awt.Color(0, 0, 255));
        aniadirSociojButton.setText("Añadir Socio");
        aniadirSociojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirSociojButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aniadirSociojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 60));

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 0, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Profesor", "Alumno" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadirsocios.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aniadirSociojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirSociojButtonActionPerformed
      
        
        String dni = dnijTextField.getText();
        String nombre = nombrejTextField.getText();
        String categoria = (String) jComboBox1.getSelectedItem();
        String contraseña = contraseniajTextField.getText();
        if ((!dni.isEmpty())&&(!nombre.isEmpty())&&(!categoria.isEmpty())&&(!contraseña.isEmpty())){
            if (!s.estaSocio(dni)){
               
                    socio = new Socio(dni, nombre, categoria, contraseña);
                    s.addSocio(socio);
                    JOptionPane.showMessageDialog(this, "EL SOCIO HA SIDO REGISTRADO CORRECTAMENTE");
                    this.dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(this, "SOCIO YA REGISTRADO");
            }
        }
        else{
           JOptionPane.showMessageDialog(this, "ERROR: DEBE RELLENAR TODOS LOS CAMPOS"); 
        }
  
    }//GEN-LAST:event_aniadirSociojButtonActionPerformed

    private void nombrejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrejTextFieldActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aniadirSociojButton;
    private javax.swing.JTextField contraseniajTextField;
    private javax.swing.JTextField dnijTextField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombrejTextField;
    // End of variables declaration//GEN-END:variables
}
