package bibliopatrones;

import Decorator_Iterator.LibreriaPublicaciones;
import FactoryMethod_Strategy.FactoriaPublicaciones;
import FactoryMethod_Strategy.Publicacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author doverride
 */
public class IzCreaPublicDialog extends javax.swing.JDialog {


    Publicacion  miPublicacion;
    LibreriaPublicaciones libreria;
   
    /**
     * Creates new form IzPublicacionDialog
     */
    public IzCreaPublicDialog(java.awt.Frame parent, boolean modal, LibreriaPublicaciones publicaciones) {
        super(parent, modal);
        initComponents();
        this.libreria = publicaciones;
        this.setVisible(true);
        
    }
    //Devuelve el objeto Publicaciones, para igualarlo al de gestion.
    public Publicacion getNuevaPublicacion(){
        return this.miPublicacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codejText = new javax.swing.JTextField();
        isbnjText = new javax.swing.JTextField();
        titulojText = new javax.swing.JTextField();
        autorjText = new javax.swing.JTextField();
        seleccionPublijComboBox = new javax.swing.JComboBox<String>();
        AnadirPubliButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        param1jText = new javax.swing.JTextField();
        param1Label = new javax.swing.JLabel();
        param3Label = new javax.swing.JLabel();
        param2Label = new javax.swing.JLabel();
        param2jText = new javax.swing.JTextField();
        param3jText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setText("ISBN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 255));
        jLabel3.setText("Título:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 255));
        jLabel4.setText("Autor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        codejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codejTextActionPerformed(evt);
            }
        });
        getContentPane().add(codejText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));
        getContentPane().add(isbnjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, -1));

        titulojText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulojTextActionPerformed(evt);
            }
        });
        getContentPane().add(titulojText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 90, -1));
        getContentPane().add(autorjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 80, -1));

        seleccionPublijComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        seleccionPublijComboBox.setForeground(new java.awt.Color(102, 0, 255));
        seleccionPublijComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libro", "Revista", "Tesis" }));
        seleccionPublijComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionPublijComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(seleccionPublijComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        AnadirPubliButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        AnadirPubliButton.setForeground(new java.awt.Color(102, 0, 255));
        AnadirPubliButton.setText("Añadir publicación");
        AnadirPubliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirPubliButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AnadirPubliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 302, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 255));
        jLabel9.setText("Crear publicación");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        param1jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param1jTextActionPerformed(evt);
            }
        });
        getContentPane().add(param1jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 90, -1));

        param1Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        param1Label.setForeground(new java.awt.Color(102, 0, 255));
        param1Label.setText("Editorial:");
        getContentPane().add(param1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 27));

        param3Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        param3Label.setForeground(new java.awt.Color(102, 0, 255));
        param3Label.setText("Edición:");
        getContentPane().add(param3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, -1));

        param2Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        param2Label.setForeground(new java.awt.Color(102, 0, 255));
        param2Label.setText("Contenido:");
        getContentPane().add(param2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));
        getContentPane().add(param2jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 90, -1));
        getContentPane().add(param3jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaslibros1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      

    private void AnadirPubliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirPubliButtonActionPerformed
        //Vamos a añadir una publicacion a partir de los text y usando la factoria        
        
        if (libreria.estaPublicacion(codejText.getText())){
                JOptionPane.showMessageDialog(this, "ERROR: La publicacion ya se encuentra registrada");
        }
        else if ((codejText.getText().isEmpty()) || (isbnjText.getText().isEmpty())|| (autorjText.getText().isEmpty())||(titulojText.getText().isEmpty())
                || (param1jText.getText().isEmpty())||(param2jText.getText().isEmpty())||(param3jText.getText().isEmpty())){
                    JOptionPane.showMessageDialog(this, "ERROR: Debe rellenar todos los campos");
        }
        else{
            FactoriaPublicaciones factoryPub = new FactoriaPublicaciones(codejText.getText(),isbnjText.getText(),titulojText.getText(),autorjText.getText());
            int seleccion = seleccionPublijComboBox.getSelectedIndex();
            switch(seleccion){           
                case 0: 
                //libro
                    miPublicacion = factoryPub.getPublicacion("Libro",this.param1jText.getText(), this.param2jText.getText(), this.param3jText.getText());
                    break;
                case 1:
                //revista
                    miPublicacion = factoryPub.getPublicacion("Revista",this.param1jText.getText(),this.param2jText.getText(), this.param3jText.getText());
                    break;
                default:
                //tesis
                    miPublicacion = factoryPub.getPublicacion("Tesis",this.param1jText.getText(),this.param2jText.getText(), this.param3jText.getText());
                    break;
            }
            JOptionPane.showMessageDialog(this, "Publicacion "+codejText.getText()+" registrada correctamente");
            libreria.addPublicacion(miPublicacion);
            this.dispose();
        }     
    }//GEN-LAST:event_AnadirPubliButtonActionPerformed

    private void seleccionPublijComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionPublijComboBoxActionPerformed
        int seleccion = seleccionPublijComboBox.getSelectedIndex();
        switch (seleccion){
            case 0:
                //Cambiar layout a libro               
                this.param1Label.setText("Editorial:");
                this.param2Label.setText("Contenido:");
                this.param3Label.setText("Edición:");
                break;
            case 1:
                //Cambiar a revista
                this.param1Label.setText("Periodicidad:");
                this.param2Label.setText("Volumen:");
                this.param3Label.setText("NºPublicación:");
                
                break;
            default:
                //Cambiar a tesis
                this.param1Label.setText("Tribunal:");
                this.param2Label.setText("Departamento:");
                this.param3Label.setText("Calificación:");
                
                break;
       }
            
    }//GEN-LAST:event_seleccionPublijComboBoxActionPerformed

    private void titulojTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulojTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulojTextActionPerformed

    private void param1jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param1jTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param1jTextActionPerformed

    private void codejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codejTextActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirPubliButton;
    private javax.swing.JTextField autorjText;
    private javax.swing.JTextField codejText;
    private javax.swing.JTextField isbnjText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel param1Label;
    private javax.swing.JTextField param1jText;
    private javax.swing.JLabel param2Label;
    private javax.swing.JTextField param2jText;
    private javax.swing.JLabel param3Label;
    private javax.swing.JTextField param3jText;
    private javax.swing.JComboBox<String> seleccionPublijComboBox;
    private javax.swing.JTextField titulojText;
    // End of variables declaration//GEN-END:variables
}
