package bibliopatrones;

import Command.CommandInterfaz;
import Command.CommandPublicIntz;
import Decorator_Iterator.ConjuntoSocios;
import FactoryMethod_Strategy.Publicacion;
import Decorator_Iterator.LibreriaPublicaciones;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author doverride
 */
public class IzMostrarPublicDialog extends javax.swing.JDialog {

    LibreriaPublicaciones publicaciones;
    ConjuntoSocios socios;
    java.awt.Frame parent;
    CommandInterfaz miInterfaz;
    /**
     * Creates new form IzMostrarPublicDialog
     */
    public IzMostrarPublicDialog(java.awt.Frame parent, boolean modal,LibreriaPublicaciones publicaciones, ConjuntoSocios socios) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.publicaciones = publicaciones;
        this.miInterfaz = new CommandPublicIntz(this);
        this.pintaPublicacion(publicaciones.primeraPubli());
        this.socios = socios;
        this.setVisible(true);
      
    }

    public LibreriaPublicaciones getPublicaciones(){
        return publicaciones;
    }
    
    private void avanzar(){
        this.pintaPublicacion(publicaciones.nextPubli());
        
    }
    private void pintaPublicacion(Publicacion publi){
        
        this.codigoLabel.setText(publi.getCodigo());
        this.isbnLabel.setText(publi.getISBN());
        this.tituloLabel.setText(publi.getTitulo());
        this.autorLabel.setText(publi.getAutores());
        if (publi.estaPrestada()){
            this.reservadoLabel.setText("No disponible");
        }else{
            this.reservadoLabel.setText("Disponible");
        }
    
        String tipo = publi.getTipo();
        switch(tipo){
            case "Libro":
                this.miInterfaz.executeUno();
//                this.tipoPubliLabel.setText("LIBRO");
//                this.param1Label.setText("Editorial");
//                this.param2Label.setText("Contenido");
//                this.param3Label.setText("Edicion");
                break;
            case "Revista":
                this.miInterfaz.executeDos();
//                this.tipoPubliLabel.setText("REVISTA");
//                this.param1Label.setText("Periodicidad");
//                this.param2Label.setText("Volumen");
//                this.param3Label.setText("NºPubli");
                break;
            default:
                this.miInterfaz.executeTres();
//                this.tipoPubliLabel.setText("TESIS");
//                this.param1Label.setText("Tribunal");
//                this.param2Label.setText("Departamento");
//                this.param3Label.setText("Calificación");
                break;
        }
                this.cParam1Label.setText(publi.getParam1());
                this.cParam2Label.setText(publi.getParam2());
                this.cParam3Label.setText(publi.getParam3());

    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        param1Label = new javax.swing.JLabel();
        param2Label = new javax.swing.JLabel();
        param3Label = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        autorLabel = new javax.swing.JLabel();
        cParam1Label = new javax.swing.JLabel();
        cParam3Label = new javax.swing.JLabel();
        cParam2Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        reservadoLabel = new javax.swing.JLabel();
        tipoPubliLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Codigo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 68, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Titulo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ISBN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 68, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Autor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        param1Label.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        param1Label.setForeground(new java.awt.Color(255, 255, 255));
        param1Label.setText("jLabel9");
        getContentPane().add(param1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        param2Label.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        param2Label.setForeground(new java.awt.Color(255, 255, 255));
        param2Label.setText("jLabel10");
        getContentPane().add(param2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        param3Label.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        param3Label.setForeground(new java.awt.Color(255, 255, 255));
        param3Label.setText("jLabel11");
        getContentPane().add(param3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        codigoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        codigoLabel.setForeground(new java.awt.Color(255, 255, 255));
        codigoLabel.setText("jLabel12");
        getContentPane().add(codigoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 68, -1, -1));

        isbnLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        isbnLabel.setForeground(new java.awt.Color(255, 255, 255));
        isbnLabel.setText("jLabel13");
        getContentPane().add(isbnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 68, -1, -1));

        tituloLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("jLabel14");
        getContentPane().add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        autorLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        autorLabel.setForeground(new java.awt.Color(255, 255, 255));
        autorLabel.setText("jLabel15");
        getContentPane().add(autorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        cParam1Label.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        cParam1Label.setForeground(new java.awt.Color(255, 255, 255));
        cParam1Label.setText("jLabel16");
        getContentPane().add(cParam1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        cParam3Label.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        cParam3Label.setForeground(new java.awt.Color(255, 255, 255));
        cParam3Label.setText("jLabel17");
        getContentPane().add(cParam3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        cParam2Label.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        cParam2Label.setForeground(new java.awt.Color(255, 255, 255));
        cParam2Label.setText("jLabel18");
        getContentPane().add(cParam2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("Prestar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 20, 107, -1));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        reservadoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        reservadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservadoLabel.setText("Disponible");
        getContentPane().add(reservadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        tipoPubliLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        tipoPubliLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipoPubliLabel.setText("jLabel2");
        getContentPane().add(tipoPubliLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 27, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros-planeta-triatlon_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.setVisible(false);
        IzCrearPrestamoDialog creaPres = new IzCrearPrestamoDialog(parent,rootPaneCheckingEnabled, socios,publicaciones.publicacionActual(),publicaciones);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.avanzar();
    }//GEN-LAST:event_jButton3ActionPerformed

    public JLabel getParam1Label() {
        return param1Label;
    }

    public JLabel getParam2Label() {
        return param2Label;
    }

    public JLabel getParam3Label() {
        return param3Label;
    }

    public JLabel getTipoPubliLabel() {
        return tipoPubliLabel;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorLabel;
    private javax.swing.JLabel cParam1Label;
    private javax.swing.JLabel cParam2Label;
    private javax.swing.JLabel cParam3Label;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel param1Label;
    private javax.swing.JLabel param2Label;
    private javax.swing.JLabel param3Label;
    private javax.swing.JLabel reservadoLabel;
    private javax.swing.JLabel tipoPubliLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
