/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Clases.Tfg;
import Clases.Usuario;
import  Singleton.Serializa;
import State.EstadoAsignado;
import State.EstadoNoAsignado;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author joserra
 */
public class InterfazAsignacionTfg extends javax.swing.JFrame {

    /**
     * Creates new form AsignacionTfg
     */
    private Serializa serializa;
    private Usuario nombreProfesor;
    private ArrayList<Tfg> listaTFG = new ArrayList<>();
    private HashMap<String,Usuario> listaUsuarios = new HashMap<>();
    public InterfazAsignacionTfg(Usuario nombreProfesor, Serializa serializa) {
        initComponents();
        this.serializa = serializa;
        this.nombreProfesor=nombreProfesor;
        cargarListaAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Listado TFGs");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Listado Alumnos");

        jButton2.setText("Desasignar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2)
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButton1)
                                .addGap(123, 123, 123)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String key1 = jList1.getSelectedValue();//Titulo Tfg
            String key2 = jList2.getSelectedValue();//nombreUsuario
            Tfg tfgSeleccionado = null;
            for(int x=0;x<listaTFG.size();x++) {
                if(listaTFG.get(x).getTitulo().equals(key1)){
                    tfgSeleccionado = listaTFG.get(x);
                }
            }
            Usuario usuarioSeleccionado = listaUsuarios.get(key2);
            
            if(usuarioSeleccionado.getAsignado()==false && tfgSeleccionado.getAsignado()==false){
                int choice =JOptionPane.showOptionDialog (this,"Desea asignar el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario()+"?", "¿Asignar?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if(choice == JOptionPane.YES_NO_OPTION){
                    usuarioSeleccionado.setAsignado(new EstadoAsignado().estado());
                    tfgSeleccionado.setAsignado(new EstadoAsignado().estado());
                    tfgSeleccionado.setAlumnoAsignado(usuarioSeleccionado.getNombreUsuario());
                    serializa.GuardarTfg(tfgSeleccionado);
                    serializa.GuardarCliente(key2, usuarioSeleccionado);
                    JOptionPane.showMessageDialog(this,"Ha sido asignado el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario());
                }
            }
            else{
               JOptionPane.showMessageDialog(this,"El alumno / TFG ya han sido previamente asignados!"); 
            }
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Selecciona un tfg y un alumno para realizar la asignación."); 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String key1 = jList1.getSelectedValue();//Titulo Tfg
            String key2 = jList2.getSelectedValue();//nombreUsuario
            Tfg tfgSeleccionado = null;
            for(int x=0;x<listaTFG.size();x++) {
                if(listaTFG.get(x).getTitulo().equals(key1)){
                    tfgSeleccionado = listaTFG.get(x);
                }
            }
            Usuario usuarioSeleccionado = listaUsuarios.get(key2);
            
            if(usuarioSeleccionado.getAsignado()==true && tfgSeleccionado.getAsignado()==true){
            
                int choice =JOptionPane.showOptionDialog (this,"Desea desasignar el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario()+"?", "¿Desasignar?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if(choice == JOptionPane.YES_NO_OPTION){
                    usuarioSeleccionado.setAsignado(new EstadoNoAsignado().estado());
                    tfgSeleccionado.setAsignado(new EstadoNoAsignado().estado());
                    serializa.GuardarTfg(tfgSeleccionado);
                    serializa.GuardarCliente(key2, usuarioSeleccionado);
                    JOptionPane.showMessageDialog(this,"Ha sido desasignado el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario()); 
                }
            }else{
               JOptionPane.showMessageDialog(this,"El alumno / TFG ya han sido previamente asignados!"); 
            }
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Selecciona un tfg y un alumno para realizar la asignación."); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(this.nombreProfesor.getNombreUsuario().equals("admin")){
            InterfazAdmin ia = new InterfazAdmin(this.nombreProfesor, this.serializa);
            this.setVisible(false);
            ia.setVisible(true);
        }else{
            InterfazProfesor ia = new InterfazProfesor(this.nombreProfesor, this.serializa);
            this.setVisible(false);
            ia.setVisible(true); 
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //cogemos alumno seleccionado y se lo pasamos
        String key2 = jList2.getSelectedValue();//nombreUsuario
        cargaDatosListaTfg(key2);
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
    public void cargaDatosListaTfg(String nombreUsuario){
        
        DefaultListModel listModel = new DefaultListModel();
        ArrayList<String> listaAlumnos;
        
        listaTFG = serializa.CargarTfg();
        Iterator<Tfg> it = listaTFG.iterator();
        while (it.hasNext()){
            Tfg key= it.next();
            if(nombreProfesor.getNombre().equals(key.getTutor()) ){
                listaAlumnos = key.getAlumno();
                if(listaAlumnos.contains(nombreUsuario)){
                    listModel.addElement(key.getTitulo());
                }
            }
        }
        jList1.setModel(listModel);
    }
    
    public void cargarListaAlumnos(){
        DefaultListModel listModel = new DefaultListModel();
        
        listaUsuarios = serializa.CargarClientes();
        Iterator it = listaUsuarios.keySet().iterator();
        while (it.hasNext()){
            String key= (String) it.next();
            Usuario ll = listaUsuarios.get(key);
            if(ll.getProfesor()==false){
                listModel.addElement(key);
            }
        }
        jList2.setModel(listModel);
    }
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
