/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Tfg;
import Clases.Usuario;
import Singleton.Serializa;
import State.EstadoAsignado;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author guillermo
 */
public class InterfazAutoasignación extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAutoasignación
     */
    private Usuario c;
    private Serializa serializa;
    private ArrayList<Tfg> listaTFG = new ArrayList<>();
    private HashMap<String, Usuario> listaUsuarios = new HashMap<String, Usuario>();
    private DefaultListModel listModel = new DefaultListModel();
    
    public InterfazAutoasignación() {
        initComponents();
    }
    
    public InterfazAutoasignación(Serializa serializa) {
        this.serializa = serializa;
        initComponents();
        this.autoAsignar();
    }

    public void autoAsignar(){
        this.listaTFG = serializa.CargarTfg();
        for(int i = 0; i<listaTFG.size();i++){
            if(this.listaTFG.get(i).getAsignado()){
                this.listModel.addElement(this.listaTFG.get(i).getAlumnoAsignado()+"\t\t"+this.listaTFG.get(i).getTitulo()+"\t\t");
            }
            Usuario userElegido = getAlumnoSeleccionado(this.listaTFG.get(i));
            this.asignar(userElegido, this.listaTFG.get(i));
        }
        if(this.listModel.isEmpty()){
            System.out.println("VACIA");
        }else{
            try{
                jListInfo.setModel(this.listModel);
            }catch(Exception e){
                System.out.println(e);
            }
           
        }
        
    }
    public void asignar(Usuario user, Tfg tfg){
        user.setAsignado(new EstadoAsignado().estado());
        tfg.setAsignado(new EstadoAsignado().estado());
        tfg.setAlumnoAsignado(user.getNombreUsuario());
        this.listModel.addElement(user.getNombreUsuario()+"\t\t"+tfg.getTitulo()+"\t\t"+user.getNotaMedia());
        serializa.GuardarTfg(tfg);
        serializa.GuardarCliente(user.getNombreUsuario(), user);
    }
    public Usuario getAlumnoSeleccionado(Tfg tfgAsignar){
        if(tfgAsignar.getAlumno().isEmpty()){
            return null;
        }else{
            listaUsuarios = serializa.CargarClientes();
            Iterator it = listaUsuarios.keySet().iterator();
            ArrayList<Usuario> notaMedia = new ArrayList<Usuario>();
            while (it.hasNext()){
                String key= (String) it.next();
                Usuario ll = listaUsuarios.get(key);
                if(ll.getProfesor()==false && tfgAsignar.getAlumno().contains(ll.getNombreUsuario())){
                    notaMedia.add(ll);
                }
            }
            Collections.sort(notaMedia, new Comparator<Usuario>() {
                @Override
                public int compare(Usuario c1, Usuario c2) {
                    return Double.compare(c2.getNotaMedia(), c1.getNotaMedia());
                }
            });
            boolean disponible = true;
            int indiceAlumno = 0;
            for(int i=0; i<notaMedia.size(); i++){
                if(disponible && !notaMedia.get(i).getAsignado()){
                    disponible = false;
                    indiceAlumno = i;
                }
            }
            return notaMedia.get(indiceAlumno);
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListInfo = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListInfo);

        jLabel1.setText("Nombre:");

        jLabel2.setText("TFG Asignado");

        jLabel3.setText("Nota media:");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame getFrame(){
        return this;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAutoasignación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAutoasignación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAutoasignación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAutoasignación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAutoasignación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListInfo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
