/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Singleton.Serializa;
import Clases.Usuario;
import java.awt.Color;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;

/**
 *
 * @author Joserra
 */
public class InterfazRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistrar
     */
    //Creamos un HashMap de la clase Cliente llamado tablaClientes
    private Serializa serializa;
    private Usuario admin;
    public InterfazRegistrar() {
        //Título de la ventana
        this.setTitle("Nuevo Registro");
        initComponents();
        NIFPersona.setText("00000000-A");
         
    }
    public InterfazRegistrar(Usuario user, Serializa serializa) {
        //Título de la ventana
        this.setTitle("Nuevo Registro");
        initComponents();
        this.jlabelNotaMedia.setVisible(false);
        this.jTextFieldNotaMedia.setVisible(false);
        NIFPersona.setText("00000000-A");
        this.admin = user;
        this.serializa = serializa;
    }
    
    
    public void guardaUsuario(Usuario u, String correo){
        
        HashMap<String, Usuario> compruebaDni = serializa.CargarClientes();
        Iterator it = compruebaDni.keySet().iterator();
        boolean checkNif = false, checkNameUser = false;
        while (it.hasNext()){
            String key= (String) it.next();
            String nif = compruebaDni.get(key).getNIF();
            String nombreUser = compruebaDni.get(key).getNombreUsuario();
            if(nif.equals(u.getNIF())){
                checkNif = true;
                this.NIFPersona.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                this.NIFPersona.setForeground(Color.RED);
                JOptionPane.showMessageDialog(this,"Ya existe un usuario con ese DNI","¡ATENCIÓN!",JOptionPane.WARNING_MESSAGE);
            }
            if(nombreUser.equals(u.getNombreUsuario())){
                checkNameUser = true;
                this.nombreUsuario.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                this.nombreUsuario.setForeground(Color.RED);
                JOptionPane.showMessageDialog(this,"Ya existe ese nombre usuario","¡ATENCIÓN!",JOptionPane.WARNING_MESSAGE);
            }
        }
        if(!checkNif && !checkNameUser){
            serializa.GuardarCliente(correo, u);    
                //Nos lleva a la ventana principal
            InterfazAdmin ip = new InterfazAdmin(this.admin, this.serializa);
            this.setVisible(false);
            ip.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombrePersona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidosPersona = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NIFPersona = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        contraseñaUsuario = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        checkProfesor = new javax.swing.JRadioButton();
        checkAlumno = new javax.swing.JRadioButton();
        jlabelNotaMedia = new javax.swing.JLabel();
        jTextFieldNotaMedia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Nuevo Usuario");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("NIF:");

        try {
            NIFPersona.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Nombre de Usuario:");

        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });

        jLabel8.setText("Contraseña:");

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo:");

        buttonGroup1.add(checkProfesor);
        checkProfesor.setSelected(true);
        checkProfesor.setText("Profesor");
        checkProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkProfesorActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkAlumno);
        checkAlumno.setText("Alumno");
        checkAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAlumnoActionPerformed(evt);
            }
        });

        jlabelNotaMedia.setText("Nota Media:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NIFPersona)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(apellidosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(checkProfesor)
                                .addGap(18, 18, 18)
                                .addComponent(checkAlumno))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addComponent(jlabelNotaMedia)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNotaMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegistrar)
                .addGap(301, 301, 301))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAtras)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(apellidosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NIFPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(checkProfesor)
                    .addComponent(checkAlumno))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabelNotaMedia)
                            .addComponent(jTextFieldNotaMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(13, 13, 13)
                .addComponent(botonRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAtras)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        // Registro de un nuvo cliente
        //Si hay algún campo vacío, lanza mensaje
        if((nombrePersona.getText().equals(""))||(apellidosPersona.getText().equals(""))||(NIFPersona.getText().equals(""))||
                (nombreUsuario.getText().equals(""))||(contraseñaUsuario.getText().equals(""))) {                
                    JOptionPane.showMessageDialog(this,"Error, hay algún campo sin rellenar. Rellene todos los campos.");
        }
        else{    
            //Declaramos variables
            Usuario cl1 = null;
            String nombre = nombrePersona.getText();
            String apellidos = apellidosPersona.getText();
            String NIF = NIFPersona.getText();
            String correo = nombreUsuario.getText();
            String contrasena = contraseñaUsuario.getText();
            boolean profesor;
            if(checkProfesor.isSelected()){
                profesor = true;
                //Instanciamos un objeto, lo añadimos al HashMap y lo guardamos en el .dat
                cl1 = new Usuario(nombre,apellidos,NIF,correo,contrasena, profesor);
            }else{
                profesor = false;
                if(isValidDouble(this.jTextFieldNotaMedia.getText())){
                   double notaMedia = Double.parseDouble(this.jTextFieldNotaMedia.getText());
                   if(notaMedia>=0 && notaMedia<=10){
                       //Instanciamos un objeto, lo añadimos al HashMap y lo guardamos en el .dat
                        cl1 = new Usuario(nombre,apellidos,NIF,correo,contrasena,notaMedia, profesor);  
                   }else{
                      this.jTextFieldNotaMedia.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                        this.jTextFieldNotaMedia.setForeground(Color.RED);
                        JOptionPane.showMessageDialog(this,"Introduzca un número entre 0 y 10","¡ATENCIÓN!",JOptionPane.WARNING_MESSAGE);
                        return; 
                   } 
                }else{
                    this.jTextFieldNotaMedia.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                    this.jTextFieldNotaMedia.setForeground(Color.RED);
                    JOptionPane.showMessageDialog(this,"La nota media no es un numero","¡ATENCIÓN!",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
            }
                
                
                guardaUsuario(cl1, correo);
                
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed
    private static boolean isValidDouble(String s) {
        boolean isValid = true;

        try {
            Double.parseDouble(s);
        } catch(NumberFormatException nfe) {
            isValid = false;
        }

        return isValid;
    }
    
    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        //Nos lleva a la ventana principal
        InterfazAdmin ip = new InterfazAdmin(this.admin, this.serializa);
        this.setVisible(false);
        ip.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void checkProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkProfesorActionPerformed
        // TODO add your handling code here:
        this.jlabelNotaMedia.setVisible(false);
        this.jTextFieldNotaMedia.setVisible(false);
    }//GEN-LAST:event_checkProfesorActionPerformed

    private void checkAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAlumnoActionPerformed
        // TODO add your handling code here:
        this.jlabelNotaMedia.setVisible(true);
        this.jTextFieldNotaMedia.setVisible(true);
    }//GEN-LAST:event_checkAlumnoActionPerformed

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioActionPerformed
    //Metodo para guardar los clientes en un .dat
    
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField NIFPersona;
    private javax.swing.JTextField apellidosPersona;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton checkAlumno;
    private javax.swing.JRadioButton checkProfesor;
    private javax.swing.JTextField contraseñaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldNotaMedia;
    private javax.swing.JLabel jlabelNotaMedia;
    private javax.swing.JTextField nombrePersona;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
