/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Tfg;
import Clases.Usuario;
import Singleton.Serializa;
import State.EstadoAsignado;
import State.EstadoNoAsignado;
import Strategy.Contexto;
import Strategy.Estrategia;
import Strategy.EstrategiaConcretaApellidos;
import Strategy.EstrategiaConcretaNombre;
import Strategy.EstrategiaConcretaNotaMedia;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author guillermo
 */
public class InterfazPrioridad extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrioirida
     */
    private Serializa serializa;
    private Usuario admin;
    private ArrayList<Tfg> listaTFG = new ArrayList<>();
    private HashMap<String,Usuario> listaUsuarios = new HashMap<>();
    
    public InterfazPrioridad() {
        initComponents();
    }
    public InterfazPrioridad(Usuario user, Serializa serializa) {
        initComponents();
        this.serializa = serializa;
        this.admin=user;
        this.cargaDatosListaTfg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Listado TFGs");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Listado Alumnos");

        jButton2.setText("Desasignar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nota Media", "Nombre", "Apellidos" }));

        jLabel3.setText("Ordenar alumnos por:");

        jButton4.setText("Ordenar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(78, 78, 78)
                        .addComponent(jButton3)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String key1 = jList2.getSelectedValue();//Titulo Tfg
            String key2 = jList1.getSelectedValue();//nombreUsuario
            Tfg tfgSeleccionado = null;
            for(int x=0;x<listaTFG.size();x++) {
                if(listaTFG.get(x).getTitulo().equals(key1)){
                    tfgSeleccionado = listaTFG.get(x);
                }
            }
            Usuario usuarioSeleccionado = listaUsuarios.get(key2.split(" ")[0]);

            if(usuarioSeleccionado.getAsignado()==false && tfgSeleccionado.getAsignado()==false){
                int choice =JOptionPane.showOptionDialog (this,"Desea asignar el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario()+"?", "¿Asignar?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if(choice == JOptionPane.YES_NO_OPTION){
                    usuarioSeleccionado.setAsignado(new EstadoAsignado().estado());
                    tfgSeleccionado.setAsignado(new EstadoAsignado().estado());
                    tfgSeleccionado.setAlumnoAsignado(usuarioSeleccionado.getNombreUsuario());
                    serializa.GuardarTfg(tfgSeleccionado);
                    serializa.GuardarCliente(key2, usuarioSeleccionado);
                    JOptionPane.showMessageDialog(this,"Ha sido asignado el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario());
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"El alumno / TFG ya han sido previamente asignados!");
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Selecciona un tfg y un alumno para realizar la asignación.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    public void cargaDatosListaTfg(){
        DefaultListModel listModel = new DefaultListModel();
        
        listaTFG = serializa.CargarTfg();
        Iterator<Tfg> it = listaTFG.iterator();
        while (it.hasNext()){
            Tfg key= it.next();
            listModel.addElement(key.getTitulo());
        }
        jList2.setModel(listModel);
    }
    
    public void cargarListaAlumnos(String Titulo){
        DefaultListModel listModel = new DefaultListModel();
        
        listaUsuarios = serializa.CargarClientes();
        Iterator it = listaUsuarios.keySet().iterator();
        Tfg tfg = listaTFG.get(this.jList2.getSelectedIndex());
        ArrayList<Usuario> listaAlumnos = new ArrayList<Usuario>();
        while (it.hasNext()){
            String key= (String) it.next();
            Usuario ll = listaUsuarios.get(key);
            if(ll.getProfesor()==false && tfg.getAlumno().contains(ll.getNombreUsuario())){
                listaAlumnos.add(ll);
            }
        }
        Collections.sort(listaAlumnos, new Comparator<Usuario>() {
            @Override
            public int compare(Usuario c1, Usuario c2) {
                return Double.compare(c2.getNotaMedia(), c1.getNotaMedia());
            }
        });
        for(int i=0; i<listaAlumnos.size();i++){
            listModel.addElement(listaAlumnos.get(i).getNombreUsuario() + " -> " + listaAlumnos.get(i).getNotaMedia());
        }
        jList1.setModel(listModel);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String key1 = jList2.getSelectedValue();//Titulo Tfg
            String key2 = jList1.getSelectedValue();//nombreUsuario
            Tfg tfgSeleccionado = null;
            for(int x=0;x<listaTFG.size();x++) {
                if(listaTFG.get(x).getTitulo().equals(key1)){
                    tfgSeleccionado = listaTFG.get(x);
                }
            }
            Usuario usuarioSeleccionado = listaUsuarios.get(key2.split(" ")[0]);
            if(usuarioSeleccionado.getAsignado()==true && tfgSeleccionado.getAsignado()==true){

                int choice =JOptionPane.showOptionDialog (this,"Desea desasignar el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario()+"?", "¿Desasignar?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if(choice == JOptionPane.YES_NO_OPTION){
                    usuarioSeleccionado.setAsignado(new EstadoNoAsignado().estado());
                    tfgSeleccionado.setAsignado(new EstadoNoAsignado().estado());
                    tfgSeleccionado.setAlumnoAsignado("");
                    serializa.GuardarTfg(tfgSeleccionado);
                    serializa.GuardarCliente(key2, usuarioSeleccionado);
                    JOptionPane.showMessageDialog(this,"Ha sido desasignado el TFG "+tfgSeleccionado.getIdTfg()+" al alumno "+usuarioSeleccionado.getNombreUsuario());
                }
            }else{
                JOptionPane.showMessageDialog(this,"¡El alumno no tiene asignado ese TFG o ningún otro!", "¡Atención!", JOptionPane.ERROR_MESSAGE);
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Selecciona un tfg y un alumno para realizar la desasignación.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//            InterfazAdmin ia = new InterfazAdmin(this.admin, this.serializa);
//            this.setVisible(false);
//            ia.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
        this.jList1.removeAll();
        cargarListaAlumnos(this.jList2.getSelectedValue());
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            DefaultListModel listModel = new DefaultListModel();

            listaUsuarios = serializa.CargarClientes();
            Iterator it = listaUsuarios.keySet().iterator();
            Tfg tfg = listaTFG.get(this.jList2.getSelectedIndex());
            ArrayList<Usuario> listaAlumnos = new ArrayList<Usuario>();
            while (it.hasNext()){
                String key= (String) it.next();
                Usuario ll = listaUsuarios.get(key);
                if(ll.getProfesor()==false && tfg.getAlumno().contains(ll.getNombreUsuario())){
                    listaAlumnos.add(ll);
                }
            }
            Estrategia est = new EstrategiaConcretaNombre();
            Contexto contexto = new Contexto(est, listaAlumnos);

            if(this.jComboBox1.getSelectedItem().equals("Nombre")){
                listaAlumnos = contexto.ejecutaEstrategia();
            }else if(this.jComboBox1.getSelectedItem().equals("Apellidos")){
                est = new EstrategiaConcretaApellidos();
                contexto.setEstrategia(est);
                listaAlumnos = contexto.ejecutaEstrategia();
            }else{
                est = new EstrategiaConcretaNotaMedia();
                contexto.setEstrategia(est);
                listaAlumnos = contexto.ejecutaEstrategia();
            }

            for(int i=0; i<listaAlumnos.size();i++){
                listModel.addElement(listaAlumnos.get(i).getNombreUsuario() + " -> " + listaAlumnos.get(i).getNotaMedia());
            }
            jList1.setModel(listModel); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Selecciona un TFG de la lista que tenga alumnos que lo hayan elegido!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrioridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrioridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrioridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrioridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrioridad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
