/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import AgenciaEmpleo.UtilAgencia;
import Interfaz.Principal;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PeCeS
 */
public class Candidatos extends javax.swing.JFrame {

    private Principal principal;
    DefaultListModel modelo = new DefaultListModel();
    
    /**
     * Creates new form Candidatos
     * @param ventana 
     */
    public Candidatos(Principal ventana) {
        principal = ventana;
        principal.setVisible(false);
        initComponents();
        UtilAgencia.mostrarCandidatos(tablaCandidatos);
        listaCNO.setModel(modelo);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCandidatos = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        labelFoto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCNO = new javax.swing.JList();
        anagrama1 = new Interfaz.Anagrama();
        btnBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPalabras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 255));
        jLabel9.setText("Candidatos");

        tablaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCandidatosMouseClicked(evt);
            }
        });
        tablaCandidatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaCandidatosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCandidatos);

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        listaCNO.setEnabled(false);
        jScrollPane2.setViewportView(listaCNO);

        btnBorrar.setText("Borrar");
        btnBorrar.setEnabled(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ocupaciones CNO-11: ");

        txtPalabras.setEditable(false);

        jLabel2.setText("Palabras Clave: ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel9)
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(btnAtras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btnBorrar)))
                        .add(35, 35, 35)
                        .add(labelFoto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2)
                            .add(txtPalabras)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 31, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(anagrama1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel9)
                                .add(30, 30, 30)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(btnAtras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .add(btnBorrar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(25, 25, 25)
                                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .add(jLabel1)
                                        .add(39, 39, 39)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel2)
                                    .add(txtPalabras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(39, 39, 39))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(labelFoto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20)))
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 528, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(anagrama1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1169, 811));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     Seleccionar Candidato y ver sus datos (Foto, cno y palabras clave)
     */
    private void tablaCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCandidatosMouseClicked
        btnBorrar.setEnabled(true);
        int row = tablaCandidatos.getSelectedRow();
        String nif = tablaCandidatos.getValueAt(row, 0).toString();
        String cno = tablaCandidatos.getValueAt(row, 8).toString();
        txtPalabras.setText(tablaCandidatos.getValueAt(row, 9).toString());
        labelFoto.setIcon(UtilAgencia.mostrarFotoCandidato(nif));
        modelo.clear();
        ArrayList acno = UtilAgencia.getNombresCNO(cno);
        for (int i = 0; i < acno.size(); i++) {
            modelo.addElement(acno.get(i).toString());
        }
        
    }//GEN-LAST:event_tablaCandidatosMouseClicked

    /**
     Borra un candidato
     */
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int row = tablaCandidatos.getSelectedRow();
        String nombre = tablaCandidatos.getValueAt(row, 1).toString();
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro que desea borrar al candidat@: "+nombre+"?", "Borrar Candidat@", JOptionPane.YES_NO_OPTION);
        
        if(respuesta == JOptionPane.YES_OPTION){
            UtilAgencia.borrarCandidatoVisor(row);
            JOptionPane.showMessageDialog(this, "Candidat@ "+nombre+" borrad@.", "Candidat@ Borrad@", JOptionPane.INFORMATION_MESSAGE);
            UtilAgencia.mostrarCandidatos(tablaCandidatos);
            modelo.clear();
            btnBorrar.setEnabled(false);
            labelFoto.setIcon(null);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     Moverse por la tabla con las teclas
     */
    private void tablaCandidatosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaCandidatosKeyReleased
       if(evt.getKeyCode() == 38) tablaCandidatosMouseClicked(null); //Flecha hacia arriba
        if(evt.getKeyCode() == 40) tablaCandidatosMouseClicked(null); //Flecha hacia arriba
    }//GEN-LAST:event_tablaCandidatosKeyReleased

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Interfaz.Anagrama anagrama1;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JList listaCNO;
    private javax.swing.JTable tablaCandidatos;
    private javax.swing.JTextField txtPalabras;
    // End of variables declaration//GEN-END:variables
}
