/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Estefania
 */
public class Gestionpublicacion extends javax.swing.JFrame {

    /**
     * Creates new form Gestionpublicacion
     */
    private GestionPrestamo Prestamo;

    public GestionPrestamo getPrestamo() {
        return Prestamo;
    }

    public void setPrestamo(GestionPrestamo Prestamo) {
        this.Prestamo = Prestamo;
    }
    private Gestionpublicaciones Publicaciones;

    public Gestionpublicaciones getPublicaciones() {
        return Publicaciones;
    }

    public void setPublicacion(Gestionpublicaciones Publicacion) {
        this.Publicaciones = Publicacion;
    }
    private Gestionsocios Socios;

    public Gestionsocios getSocios() {
        return Socios;
    }

    public void setSocios(Gestionsocios Socios) {
        this.Socios = Socios;
    }
    private JFrame principal;

    public Gestionpublicacion(JFrame ventana, GestionPrestamo Prestamo, Gestionpublicaciones Publicacion, Gestionsocios Socios) {
        initComponents();
        this.Publicaciones = Publicacion;
        this.Socios = Socios;
        this.Prestamo = Prestamo;
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        this.jLabel22.setVisible(false);
        this.jLabel2.setVisible(false);
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jLabel6.setVisible(false);
        this.jLabel7.setVisible(false);
        this.jLabel8.setVisible(false);
        this.jLabel9.setVisible(false);
        this.jLabel10.setVisible(false);
        this.jLabel11.setVisible(false);
        this.jLabel12.setVisible(false);
        this.jLabel13.setVisible(false);
        this.jLabel23.setVisible(true);
        this.jLabel15.setVisible(false);
        this.jLabel16.setVisible(false);
        this.jLabel17.setVisible(false);
        this.jLabel18.setVisible(false);
        this.jLabel19.setVisible(false);
        this.jLabel20.setVisible(false);
        this.jTextField1.setVisible(false);
        this.jTextField2.setVisible(false);
        this.jTextField3.setVisible(false);
        this.jTextField4.setVisible(false);
        this.jTextField5.setVisible(false);
        this.jTextField6.setVisible(false);
        this.jTextField7.setVisible(false);
        this.jTextField8.setVisible(false);
        this.jTextField10.setVisible(false);
        this.jTextField11.setVisible(false);
        this.jTextField12.setVisible(false);
        this.jTextField13.setVisible(false);
        this.jTextField14.setVisible(false);
        this.jTextField15.setVisible(false);
        this.jTextField16.setVisible(false);
        this.jTextField17.setVisible(false);
        this.jTextField18.setVisible(false);
        this.jComboBox2.setVisible(false);
        this.jComboBox3.setVisible(false);
        this.jButton3.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BIBLIOTECA UNIVERSITARIA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Menú principal");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("PUBLICACIONES");

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 51, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Alta publicaciones", "Baja publicaciones", "Consulta publicaciones", "Modificación publicaciones", "Préstamo", "Devolución" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("ISBN");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Titulo");

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Autores");

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Dia");

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Mes");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Año");

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Paginas");

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Colección");

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Foto");

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Materia");

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Observaciones");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Libros", "Revistas", "Proyectos", "Tesis" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Departamento");

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("Tribunal");

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Entidad");

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("Calificacion");

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Fechalectura");

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Titulación");

        jButton3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Dar de alta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Tipo operación");

        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Tipo publicación");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sí", "No" }));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Biblioteca/uah.jpg"))); // NOI18N
        jLabel23.setMaximumSize(new java.awt.Dimension(50, 70));
        jLabel23.setMinimumSize(new java.awt.Dimension(30, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-500)/2, 700, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Gestion pantalla = new Gestion(this);
        pantalla.setPrestamo(Prestamo);
        pantalla.setPublicacion(Publicaciones);
        pantalla.setSocios(Socios);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String cadena = (String) this.jComboBox1.getSelectedItem();


        if (cadena.equals("Alta publicaciones")) {


            try {
                String Codigo = (String) this.jTextField1.getText();
                String ISBN = (String) this.jTextField2.getText();
                String Titulo = (String) this.jTextField3.getText();
                String Autor = (String) this.jTextField4.getText();
                int dia = Integer.parseInt(this.jTextField5.getText());
                if ((dia < 1) || (dia > 31)) {
                    throw new Bibliotecaexception(Bibliotecaexception.DIA_ERROR);
                }
                int mes = Integer.parseInt(this.jTextField6.getText());
                if ((mes < 1) || (mes > 12)) {
                    throw new Bibliotecaexception(Bibliotecaexception.MES_ERROR);
                }
                int year = Integer.parseInt(this.jTextField7.getText());
                if (year > 2012) {
                    throw new Bibliotecaexception(Bibliotecaexception.AÑO_SUPER);
                }
                GregorianCalendar g = new GregorianCalendar(year, mes--, dia, 0, 0, 0);
                String foto = (String) this.jTextField18.getText();
                int Paginas = Integer.parseInt(this.jTextField8.getText());
                String coleccion = (String) this.jComboBox3.getSelectedItem();

                String materia = (String) this.jTextField11.getText();
                String observaciones = (String) this.jTextField10.getText();
                String tipo_pub = (String) this.jComboBox2.getSelectedItem();
                if (tipo_pub.equals("Libros")) {

                    String editorial = (String) this.jTextField12.getText();
                    String localidad = (String) this.jTextField13.getText();
                    String contenido = (String) this.jTextField14.getText();
                    int edicion = Integer.parseInt(this.jTextField15.getText());
                    String localizacion = (String) this.jTextField16.getText();

                    Libros l = new Libros(editorial, localidad, contenido, edicion, localizacion, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Altapublicaciones(l);
                    JOptionPane.showMessageDialog(this, "Libro dado de alta", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else if (tipo_pub.equals("Revistas")) {
                    String Periodicidad = (String) this.jTextField12.getText();
                    int Volumen = Integer.parseInt(this.jTextField13.getText());
                    int Numero = Integer.parseInt(this.jTextField14.getText());
                    int año = Integer.parseInt(this.jTextField15.getText());
                    GregorianCalendar gr = new GregorianCalendar(año, 0, 0, 0, 0, 0);
                    String localizacion = (String) this.jTextField16.getText();
                    Revistas r = new Revistas(Periodicidad, Volumen, Numero, gr, localizacion, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Altapublicaciones(r);
                    JOptionPane.showMessageDialog(this, "Revista dada de alta", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else if (tipo_pub.equals("Proyectos")) {
                    String Tribunal = (String) this.jTextField12.getText();
                    String Entidad = (String) this.jTextField13.getText();
                    String Departamento = (String) this.jTextField14.getText();
                    double Calificación = Double.parseDouble(this.jTextField15.getText());
                    String cadena_fecha = (String) this.jTextField16.getText();
                    dia = Integer.parseInt(cadena_fecha.substring(0, 2));
                    mes = Integer.parseInt(cadena_fecha.substring(3, 5));
                    year = Integer.parseInt(cadena_fecha.substring(6, 10));
                    GregorianCalendar gr = new GregorianCalendar(year, mes--, dia, 0, 0, 0);

                    String Titulación = (String) this.jTextField17.getText();
                    Proyectos p = new Proyectos(Titulación, Tribunal, Entidad, Departamento, Calificación, gr, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Altapublicaciones(p);
                    JOptionPane.showMessageDialog(this, "Proyecto dado de alta", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String Tribunal = (String) this.jTextField12.getText();
                    String Entidad = (String) this.jTextField13.getText();
                    String Departamento = (String) this.jTextField14.getText();
                    double Calificación = Double.parseDouble(this.jTextField15.getText());
                    String cadena_fecha = (String) this.jTextField16.getText();
                    dia = Integer.parseInt(cadena_fecha.substring(0, 2));
                    mes = Integer.parseInt(cadena_fecha.substring(3, 5));
                    year = Integer.parseInt(cadena_fecha.substring(6, 10));
                    GregorianCalendar gr = new GregorianCalendar(year, mes--, dia, 0, 0, 0);
                    String Programa = (String) this.jTextField17.getText();
                    Tesis t = new Tesis(Programa, Tribunal, Entidad, Departamento, Calificación, gr, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Altapublicaciones(t);
                    JOptionPane.showMessageDialog(this, "Tesis dada de alta", "Información", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } else if (cadena.equals("Baja publicaciones")) {
            String codigo = (String) this.jTextField1.getText();
            try {
                this.Publicaciones.Bajapublicaciones(codigo);

                JOptionPane.showMessageDialog(this, "Publicación dada de baja", "Información", JOptionPane.INFORMATION_MESSAGE);


            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);

            }


        } else if (cadena.equals("Consulta publicaciones")) {
            String titulo = jTextField3.getText();
            ArrayList<Publicaciones> pubs = this.Publicaciones.Consultapublicaciones(titulo);
            if (pubs.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron resultados", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                Consulta c = new Consulta(pubs, this, Prestamo, Publicaciones, Socios);
                c.setVisible(true);

            }
            //Consulta c = new Consulta (this);

        } else if (cadena.equals("Modificación publicaciones")) {
            try {
                String Codigo = (String) this.jTextField1.getText();
                String ISBN = (String) this.jTextField2.getText();
                String Titulo = (String) this.jTextField3.getText();
                String Autor = (String) this.jTextField4.getText();
                int dia = Integer.parseInt(this.jTextField5.getText());
                if ((dia < 1) || (dia > 31)) {
                    throw new Bibliotecaexception(Bibliotecaexception.DIA_ERROR);
                }
                int mes = Integer.parseInt(this.jTextField6.getText());
                if ((mes < 1) || (mes > 12)) {
                    throw new Bibliotecaexception(Bibliotecaexception.MES_ERROR);
                }
                int year = Integer.parseInt(this.jTextField7.getText());
                if (year > 2012) {
                    throw new Bibliotecaexception(Bibliotecaexception.AÑO_SUPER);
                }
                GregorianCalendar g = new GregorianCalendar(year, mes--, dia, 0, 0, 0);
                String foto = (String) this.jTextField18.getText();
                int Paginas = Integer.parseInt(this.jTextField8.getText());
                String coleccion = (String) this.jComboBox3.getSelectedItem();

                String materia = (String) this.jTextField11.getText();
                String observaciones = (String) this.jTextField10.getText();
                String tipo_pub = (String) this.jComboBox2.getSelectedItem();
                if (tipo_pub.equals("Libros")) {

                    String editorial = (String) this.jTextField12.getText();
                    String localidad = (String) this.jTextField13.getText();
                    String contenido = (String) this.jTextField14.getText();
                    int edicion = Integer.parseInt(this.jTextField15.getText());
                    String localizacion = (String) this.jTextField16.getText();

                    Libros l = new Libros(editorial, localidad, contenido, edicion, localizacion, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Modificacionpublicaciones(l);
                    JOptionPane.showMessageDialog(this, "Libro modificado", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else if (tipo_pub.equals("Revistas")) {
                    String Periodicidad = (String) this.jTextField12.getText();
                    int Volumen = Integer.parseInt(this.jTextField13.getText());
                    int Numero = Integer.parseInt(this.jTextField14.getText());
                    int año = Integer.parseInt(this.jTextField15.getText());
                    GregorianCalendar gr = new GregorianCalendar(año, 0, 0, 0, 0, 0);
                    String localizacion = (String) this.jTextField16.getText();
                    Revistas r = new Revistas(Periodicidad, Volumen, Numero, gr, localizacion, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Modificacionpublicaciones(r);
                    JOptionPane.showMessageDialog(this, "Revista modificada", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else if (tipo_pub.equals("Proyectos")) {
                    String Tribunal = (String) this.jTextField12.getText();
                    String Entidad = (String) this.jTextField13.getText();
                    String Departamento = (String) this.jTextField14.getText();
                    double Calificación = Double.parseDouble(this.jTextField15.getText());
                    String cadena_fecha = (String) this.jTextField16.getText();
                    dia = Integer.parseInt(cadena_fecha.substring(0, 1));
                    mes = Integer.parseInt(cadena_fecha.substring(3, 4));
                    year = Integer.parseInt(cadena_fecha.substring(6, 9));
                    GregorianCalendar gr = new GregorianCalendar(year, mes--, dia, 0, 0, 0);

                    String Titulación = (String) this.jTextField17.getText();
                    Proyectos p = new Proyectos(Titulación, Tribunal, Entidad, Departamento, Calificación, gr, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Modificacionpublicaciones(p);
                    JOptionPane.showMessageDialog(this, "Proyecto modificado", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String Tribunal = (String) this.jTextField12.getText();
                    String Entidad = (String) this.jTextField13.getText();
                    String Departamento = (String) this.jTextField14.getText();
                    double Calificación = Double.parseDouble(this.jTextField15.getText());
                    String cadena_fecha = (String) this.jTextField16.getText();
                    dia = Integer.parseInt(cadena_fecha.substring(0, 1));
                    mes = Integer.parseInt(cadena_fecha.substring(3, 4));
                    year = Integer.parseInt(cadena_fecha.substring(6, 9));
                    GregorianCalendar gr = new GregorianCalendar(year, mes--, dia, 0, 0, 0);
                    String Programa = (String) this.jTextField17.getText();
                    Tesis t = new Tesis(Programa, Tribunal, Entidad, Departamento, Calificación, gr, Codigo, ISBN, Titulo, Autor, g, foto, Paginas, coleccion, materia, observaciones);
                    this.Publicaciones.Modificacionpublicaciones(t);
                    JOptionPane.showMessageDialog(this, "Tesis modificado", "Información", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }



        } else if (cadena.equals("Préstamo")) {
            try {
                String cod_pub = jTextField2.getText();
                String cod_soc = jTextField1.getText();
                GregorianCalendar g = new GregorianCalendar(Locale.ROOT);
                Prestamo p = new Prestamo(cod_soc, cod_pub, g);
                this.Prestamo.Realizarprestamo(p);
                JOptionPane.showMessageDialog(this, "Publicacion prestada correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                this.Prestamo.crearTicket("PRESTAMO",cod_soc, cod_pub);     
               

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            try {
                String cod_pub = jTextField1.getText();
                String tipo_pub=this.Publicaciones.getTipoPublicacion(cod_pub);
                this.Prestamo.Devolverprestamo(cod_pub, tipo_pub);
                JOptionPane.showMessageDialog(this, "Publicacion devuelta correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }


        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:

        this.principal.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String cadena = (String) this.jComboBox1.getSelectedItem();
        if (cadena.equals("Alta publicaciones")) {

            this.jLabel22.setVisible(true);
            this.jLabel2.setVisible(true);
            this.jLabel2.setText("Código");
            this.jLabel3.setVisible(true);
            this.jLabel3.setText("ISBN");
            this.jLabel4.setVisible(true);
            this.jLabel5.setVisible(true);
            this.jLabel6.setVisible(true);
            this.jLabel7.setVisible(true);
            this.jLabel8.setVisible(true);
            this.jLabel9.setVisible(true);
            this.jLabel10.setVisible(true);
            this.jLabel11.setVisible(true);
            this.jLabel12.setVisible(true);
            this.jLabel13.setVisible(true);
            this.jLabel23.setVisible(true);
            this.jLabel15.setVisible(false);
            this.jLabel16.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField1.setVisible(true);
            this.jTextField2.setVisible(true);
            this.jTextField3.setVisible(true);
            this.jTextField4.setVisible(true);
            this.jTextField5.setVisible(true);
            this.jTextField6.setVisible(true);
            this.jTextField7.setVisible(true);
            this.jTextField8.setVisible(true);
            this.jTextField10.setVisible(true);
            this.jTextField11.setVisible(true);
            this.jTextField12.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jTextField17.setVisible(false);
            this.jTextField18.setVisible(true);
            this.jComboBox2.setVisible(true);
            this.jComboBox3.setVisible(true);
            this.jButton3.setVisible(true);
            this.jButton3.setText("Dar de alta");
        } else if (cadena.equals("Baja publicaciones")) {

            this.jLabel22.setVisible(false);
            this.jLabel2.setVisible(true);
            this.jLabel3.setVisible(false);
            this.jLabel4.setVisible(false);
            this.jLabel5.setVisible(false);
            this.jLabel6.setVisible(false);
            this.jLabel7.setVisible(false);
            this.jLabel8.setVisible(false);
            this.jLabel9.setVisible(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            this.jLabel23.setVisible(true);
            this.jLabel15.setVisible(false);
            this.jLabel16.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField1.setVisible(true);
            this.jTextField2.setVisible(false);
            this.jTextField3.setVisible(false);
            this.jTextField4.setVisible(false);
            this.jTextField5.setVisible(false);
            this.jTextField6.setVisible(false);
            this.jTextField7.setVisible(false);
            this.jTextField8.setVisible(false);
            this.jTextField10.setVisible(false);
            this.jTextField11.setVisible(false);
            this.jTextField12.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jTextField17.setVisible(false);
            this.jTextField18.setVisible(false);
            this.jComboBox2.setVisible(false);
            this.jComboBox3.setVisible(false);
            this.jButton3.setVisible(true);
            this.jButton3.setText("Dar de baja");
        } else if (cadena.equals("Consulta publicaciones")) {

            this.jLabel22.setVisible(false);
            this.jLabel2.setVisible(false);
            this.jLabel3.setVisible(false);
            this.jLabel4.setVisible(true);
            this.jLabel5.setVisible(false);
            this.jLabel6.setVisible(false);
            this.jLabel7.setVisible(false);
            this.jLabel8.setVisible(false);
            this.jLabel9.setVisible(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            this.jLabel23.setVisible(true);
            this.jLabel15.setVisible(false);
            this.jLabel16.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField1.setVisible(false);
            this.jTextField2.setVisible(false);
            this.jTextField3.setVisible(true);
            this.jTextField4.setVisible(false);
            this.jTextField5.setVisible(false);
            this.jTextField6.setVisible(false);
            this.jTextField7.setVisible(false);
            this.jTextField8.setVisible(false);
            this.jTextField10.setVisible(false);
            this.jTextField11.setVisible(false);
            this.jTextField12.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jTextField17.setVisible(false);
            this.jTextField18.setVisible(false);
            this.jComboBox2.setVisible(false);
            this.jComboBox3.setVisible(false);
            this.jButton3.setVisible(true);
            this.jButton3.setText("Pulse para consultar");
        } else if (cadena.equals("Modificación publicaciones")) {

            this.jLabel22.setVisible(true);
            this.jLabel2.setVisible(true);
            this.jLabel3.setVisible(true);
            this.jLabel4.setVisible(true);
            this.jLabel5.setVisible(true);
            this.jLabel6.setVisible(true);
            this.jLabel7.setVisible(true);
            this.jLabel8.setVisible(true);
            this.jLabel9.setVisible(true);
            this.jLabel10.setVisible(true);
            this.jLabel11.setVisible(true);
            this.jLabel12.setVisible(true);
            this.jLabel13.setVisible(true);
            this.jLabel23.setVisible(true);
            this.jLabel15.setVisible(false);
            this.jLabel16.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField1.setVisible(true);
            this.jTextField2.setVisible(true);
            this.jTextField3.setVisible(true);
            this.jTextField4.setVisible(true);
            this.jTextField5.setVisible(true);
            this.jTextField6.setVisible(true);
            this.jTextField7.setVisible(true);
            this.jTextField8.setVisible(true);
            this.jTextField10.setVisible(true);
            this.jTextField11.setVisible(true);
            this.jTextField12.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jTextField17.setVisible(false);
            this.jTextField18.setVisible(true);
            this.jComboBox2.setVisible(true);
            this.jComboBox3.setVisible(true);
            this.jButton3.setVisible(true);
            this.jButton3.setText("Modificar");
        } else if (cadena.equals("Préstamo")) {

            this.jLabel22.setVisible(false);
            this.jLabel2.setVisible(true);
            this.jLabel2.setText("Código usuario");
            this.jLabel3.setVisible(true);
            this.jLabel3.setText("Código publicación");
            this.jLabel4.setVisible(false);
            this.jLabel5.setVisible(false);
            this.jLabel6.setVisible(false);
            this.jLabel7.setVisible(false);
            this.jLabel8.setVisible(false);
            this.jLabel9.setVisible(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            this.jLabel23.setVisible(true);
            this.jLabel15.setVisible(false);
            this.jLabel16.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField1.setVisible(true);
            this.jTextField2.setVisible(true);
            this.jTextField3.setVisible(false);
            this.jTextField4.setVisible(false);
            this.jTextField5.setVisible(false);
            this.jTextField6.setVisible(false);
            this.jTextField7.setVisible(false);
            this.jTextField8.setVisible(false);
            this.jTextField10.setVisible(false);
            this.jTextField11.setVisible(false);
            this.jTextField12.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jTextField17.setVisible(false);
            this.jTextField18.setVisible(false);
            this.jComboBox2.setVisible(false);
            this.jComboBox3.setVisible(false);
            this.jButton3.setVisible(true);
            this.jButton3.setText("Prestar");
        } else if (cadena.equals("Devolución")) {

            this.jLabel22.setVisible(false);
            this.jLabel2.setVisible(true);
            this.jLabel2.setText("Código publicacion");
            this.jLabel3.setVisible(false);
            this.jLabel4.setVisible(false);
            this.jLabel5.setVisible(false);
            this.jLabel6.setVisible(false);
            this.jLabel7.setVisible(false);
            this.jLabel8.setVisible(false);
            this.jLabel9.setVisible(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            this.jLabel23.setVisible(true);
            this.jLabel15.setVisible(false);
            this.jLabel16.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField1.setVisible(true);
            this.jTextField2.setVisible(false);
            this.jTextField3.setVisible(false);
            this.jTextField4.setVisible(false);
            this.jTextField5.setVisible(false);
            this.jTextField6.setVisible(false);
            this.jTextField7.setVisible(false);
            this.jTextField8.setVisible(false);
            this.jTextField10.setVisible(false);
            this.jTextField11.setVisible(false);
            this.jTextField12.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jTextField17.setVisible(false);
            this.jTextField18.setVisible(false);
            this.jComboBox2.setVisible(false);
            this.jComboBox3.setVisible(false);
            this.jButton3.setVisible(true);
            this.jButton3.setText("Devolver");
        } else {

            this.jLabel22.setVisible(false);
            this.jLabel2.setVisible(false);
            this.jLabel3.setVisible(false);
            this.jLabel4.setVisible(false);
            this.jLabel5.setVisible(false);
            this.jLabel6.setVisible(false);
            this.jLabel7.setVisible(false);
            this.jLabel8.setVisible(false);
            this.jLabel9.setVisible(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            this.jLabel23.setVisible(true);
            this.jLabel15.setVisible(false);
            this.jLabel16.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField1.setVisible(false);
            this.jTextField2.setVisible(false);
            this.jTextField3.setVisible(false);
            this.jTextField4.setVisible(false);
            this.jTextField5.setVisible(false);
            this.jTextField6.setVisible(false);
            this.jTextField7.setVisible(false);
            this.jTextField8.setVisible(false);
            this.jTextField10.setVisible(false);
            this.jTextField11.setVisible(false);
            this.jTextField12.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jTextField17.setVisible(false);
            this.jTextField18.setVisible(false);
            this.jComboBox2.setVisible(false);
            this.jComboBox3.setVisible(false);
            this.jButton3.setVisible(false);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String cadena1 = (String) this.jComboBox2.getSelectedItem();
        if (cadena1.equals("Libros")) {
            this.jLabel16.setVisible(true);
            this.jLabel16.setText("Editorial");
            this.jTextField12.setVisible(true);
            this.jLabel17.setVisible(true);
            this.jLabel17.setText("Localidad");
            this.jTextField13.setVisible(true);
            this.jLabel15.setVisible(true);
            this.jLabel15.setText("Contenido");
            this.jTextField14.setVisible(true);
            this.jLabel18.setVisible(true);
            this.jLabel18.setText("Edición");
            this.jTextField15.setVisible(true);
            this.jLabel19.setVisible(true);
            this.jLabel19.setText("Localización");
            this.jTextField16.setVisible(true);
            this.jTextField16.setText("");
            this.jLabel20.setVisible(false);
            this.jTextField17.setVisible(false);
        } else if (cadena1.equals("Revistas")) {
            this.jLabel16.setVisible(true);
            this.jLabel16.setText("Periodicidad");
            this.jTextField12.setVisible(true);
            this.jLabel17.setVisible(true);
            this.jLabel17.setText("Volumen");
            this.jTextField13.setVisible(true);
            this.jLabel15.setVisible(true);
            this.jLabel15.setText("Número");
            this.jTextField14.setVisible(true);
            this.jLabel18.setVisible(true);
            this.jLabel18.setText("Año Disponible");
            this.jTextField15.setVisible(true);
            this.jLabel19.setVisible(true);
            this.jLabel19.setText("Localización");
            this.jTextField16.setVisible(true);
            this.jTextField16.setText("");
            this.jLabel20.setVisible(false);
            this.jTextField17.setVisible(false);
        } else if (cadena1.equals("Proyectos")) {
            this.jLabel16.setVisible(true);
            this.jLabel16.setText("Tribunal");
            this.jTextField12.setVisible(true);
            this.jLabel17.setVisible(true);
            this.jLabel17.setText("Entidad");
            this.jTextField13.setVisible(true);
            this.jLabel15.setVisible(true);
            this.jLabel15.setText("Departamento");
            this.jTextField14.setVisible(true);
            this.jLabel18.setVisible(true);
            this.jLabel18.setText("Calificación");
            this.jTextField15.setVisible(true);
            this.jLabel19.setVisible(true);
            this.jLabel19.setText("FechaLectura");
            this.jTextField16.setVisible(true);
            this.jTextField16.setText("dd/mm/aaaa");
            this.jLabel20.setVisible(true);
            this.jTextField17.setVisible(true);
        } else if (cadena1.equals("Tesis")) {
            this.jLabel16.setVisible(true);
            this.jLabel16.setText("Tribunal");
            this.jTextField12.setVisible(true);
            this.jLabel17.setVisible(true);
            this.jLabel17.setText("Entidad");
            this.jTextField13.setVisible(true);
            this.jLabel15.setVisible(true);
            this.jLabel15.setText("Departamento");
            this.jTextField14.setVisible(true);
            this.jLabel18.setVisible(true);
            this.jLabel18.setText("Calificación");
            this.jTextField15.setVisible(true);
            this.jLabel19.setVisible(true);
            this.jLabel19.setText("FechaLectura");
            this.jTextField16.setVisible(true);
            this.jTextField16.setText("dd/mm/aaaa");
            this.jLabel20.setVisible(true);
            this.jLabel20.setText("Programa");
            this.jTextField17.setVisible(true);
        } else {
            this.jLabel16.setVisible(false);
            this.jTextField12.setVisible(false);
            this.jLabel17.setVisible(false);
            this.jTextField13.setVisible(false);
            this.jLabel15.setVisible(false);
            this.jTextField14.setVisible(false);
            this.jLabel18.setVisible(false);
            this.jTextField15.setVisible(false);
            this.jLabel19.setVisible(false);
            this.jTextField16.setVisible(false);
            this.jLabel20.setVisible(false);
            this.jTextField17.setVisible(false);

        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.Socios.serializacion();
        this.Publicaciones.serializacion();
        this.Prestamo.serializacion();
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
