/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Oferta;
import Clases.Oficina;
import AgenciaEmpleo.UtilAgencia;
import java.io.File;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author PeCeS
 */
public class NuevaOferta extends javax.swing.JFrame {

    private Principal principal;
    
    /**
     * Creates new form NuevaOferta
     * @param ventana 
     */
    public NuevaOferta(Principal ventana) {
        principal = ventana;
        principal.setVisible(false);
        initComponents();
        rellenarCNO();
        cbOcu.setSelectedItem(0);
        
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbParcial = new javax.swing.JRadioButton();
        rbCompleto = new javax.swing.JRadioButton();
        cbOficina = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        anagrama1 = new Interfaz.Anagrama();
        jLabel10 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnNuevaOfi = new javax.swing.JButton();
        cbOcu = new javax.swing.JComboBox();
        txtFofe = new javax.swing.JFormattedTextField();
        txtFcad = new javax.swing.JFormattedTextField();
        txtPalabras = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        txtFoto = new javax.swing.JTextField();
        txtRango = new javax.swing.JTextField();
        txtDispo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nombre Empresa: ");

        jLabel2.setText("Oficina: ");

        jLabel3.setText("Ocupación CNO-11: ");

        jLabel4.setText("Palabras Clave: ");

        jLabel5.setText("Fecha Oferta: ");

        jLabel6.setText("Fecha Caducidad: ");

        jLabel7.setText("Rango Salarial (Anual): ");

        jLabel8.setText("Tiempo: ");

        buttonGroup1.add(rbParcial);
        rbParcial.setText("Parcial");
        rbParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParcialActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCompleto);
        rbCompleto.setSelected(true);
        rbCompleto.setText("Completo");
        rbCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompletoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 255));
        jLabel9.setText("Nueva Oferta de Empleo");

        jLabel10.setText("Disposición: ");

        btnAgregar.setText("Recibir");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnNuevaOfi.setText("Nueva Oficina");
        btnNuevaOfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaOfiActionPerformed(evt);
            }
        });

        try {
            txtFofe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFcad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtPalabras.setToolTipText("Aaaa,Aaaa,Aaaa");

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel11.setText("Agregar Foto: ");

        btnFoto.setText("Agregar Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        txtFoto.setEditable(false);

        txtRango.setToolTipText("00000-00000");

        txtDispo.setEnabled(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(anagrama1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel9)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel1)
                                    .add(jLabel2))
                                .add(246, 246, 246))))
                    .add(layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(btnAtras)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btnAgregar))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jLabel6)
                                            .add(jLabel5))
                                        .add(246, 246, 246)))
                                .add(198, 198, 198))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4))
                                .add(44, 44, 44)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(6, 6, 6)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(txtPalabras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 394, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtDispo)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                        .add(rbCompleto)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .add(rbParcial))
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtFcad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtFofe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtRango))
                                                .add(36, 36, 36)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                    .add(jLabel11)
                                                    .add(btnFoto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(txtFoto)))))
                                    .add(txtNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 407, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(layout.createSequentialGroup()
                                            .add(cbOficina, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(btnNuevaOfi))
                                        .add(cbOcu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(11, 11, 11))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel8)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10))
                                .add(450, 450, 450)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(cbOficina, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnNuevaOfi))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(cbOcu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txtPalabras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txtFofe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txtFcad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnFoto))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(txtFoto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtRango, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(rbCompleto)
                    .add(rbParcial))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(txtDispo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAgregar)
                    .add(btnAtras))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(anagrama1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-687)/2, (screenSize.height-566)/2, 687, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     JDialog para crear una nueva Oficina
     */
    private void btnNuevaOfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaOfiActionPerformed
        new NuevaOficina(this, true).setVisible(true);
    }//GEN-LAST:event_btnNuevaOfiActionPerformed

    private void rbCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompletoActionPerformed
        txtDispo.setText("");
        txtDispo.setEnabled(false);
    }//GEN-LAST:event_rbCompletoActionPerformed

    private void rbParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParcialActionPerformed
        txtDispo.setEnabled(true);
    }//GEN-LAST:event_rbParcialActionPerformed
    /**
     Agrega la Oferta con los datos que hemos recibido
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        try{
            int rango = Integer.parseInt(txtRango.getText().substring(0,5));
            String cnoo = cbOcu.getSelectedItem().toString();
            String oficina = cbOficina.getSelectedItem().toString().substring(0, 4);
            String empresa = txtNombre.getText().substring(0,4);
                    if(oficina.equals(empresa)){
                    
                
                        if( UtilAgencia.comprobarListaCNOOferta(cnoo)) {
                            Oficina ofi = UtilAgencia.getOficina(cbOficina.getSelectedItem().toString());
                            String dirFoto = "img/"+txtFoto.getText();
                            Oferta of;
                            String cno = cbOcu.getSelectedItem().toString().substring(0,4);
                            //Sacar las fechas
                            String [] fo = txtFofe.getText().split("/");
                            String [] fc = txtFcad.getText().split("/");
                            int mesO = Integer.parseInt(fo[1]); mesO--;
                            int mesC = Integer.parseInt(fc[1]); mesC--;
                            GregorianCalendar fofe = new GregorianCalendar(Integer.parseInt(fo[2]), mesO, Integer.parseInt(fo[0]));
                            GregorianCalendar fcad = new GregorianCalendar(Integer.parseInt(fc[2]), mesC, Integer.parseInt(fc[0]));
                            String dispo = txtDispo.getText();
                            if(rbParcial.isSelected() && Integer.parseInt(dispo) > 100) dispo = "100";
                            if(rbCompleto.isSelected()){
                                of = new Oferta(txtNombre.getText(), ofi, cno, txtPalabras.getText(), fofe, fcad, txtRango.getText(),"Completo",dirFoto, 0);
                            }else{
                                of = new Oferta(txtNombre.getText(), ofi, cno, txtPalabras.getText(), fofe, fcad, txtRango.getText(), "Parcial",dirFoto, Integer.parseInt(dispo));
                            }
                            UtilAgencia.nuevaOferta(of);
                            JOptionPane.showMessageDialog(this, "Oferta de "+txtNombre.getText()+" agregada", "Oferta Agregada", JOptionPane.INFORMATION_MESSAGE);
                            limpiarCampos();
                        }else{
                            JOptionPane.showMessageDialog(this, "Introduzca bien el Rango Salarial.", "Erorr", JOptionPane.ERROR_MESSAGE);
                        }
                    }else
                    {
                        JOptionPane.showMessageDialog(this, "Introduzca bien oficina.", "Erorr", JOptionPane.ERROR_MESSAGE);
                    }
           
        }catch(NullPointerException e){JOptionPane.showMessageDialog(this, "Introduzca bien los datos.", "Erorr", JOptionPane.ERROR_MESSAGE);}
        catch(NumberFormatException e){JOptionPane.showMessageDialog(this, "Introduzca bien los datos.", "Error", JOptionPane.ERROR_MESSAGE);}
        catch(Exception e){JOptionPane.showMessageDialog(this, "Error: Introduzca todos los datos \n"+e.toString(), "Error", JOptionPane.INFORMATION_MESSAGE);}
    
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed
    /**
     Abre una ventana para seleccionar una foto
     */
    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
           File fichero = fileChooser.getSelectedFile();
           if(!fichero.getName().contains(".png")){
               JOptionPane.showMessageDialog(this, "Introduce un archivo correcto", "Error de Archivo", JOptionPane.INFORMATION_MESSAGE);
           }
           else{
            txtFoto.setText(fichero.getName());
           }
        }
    }//GEN-LAST:event_btnFotoActionPerformed
    /**
     Rellena los combobox cno y oficinas
     */
    public void rellenarCNO(){
            ArrayList al = UtilAgencia.getOcupacionCNO();
            for (int i = 0; i < al.size(); i++) {
                cbOcu.addItem(al.get(i));
            }
            ArrayList<Oficina> o = UtilAgencia.getOficinas();
                for (int i = 0; i < o.size(); i++) {
                    cbOficina.addItem(o.get(i).getNombre());
                }
            if(!o.isEmpty()) {
                cbOficina.setSelectedIndex(0);
            }
        
    }
    
    private void limpiarCampos(){
        txtNombre.setText("");
        cbOcu.setSelectedIndex(0);
        txtPalabras.setText("");
        txtFofe.setText("");
        txtFcad.setText("");
        txtRango.setText("");
        txtDispo.setText("");
        txtFoto.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Interfaz.Anagrama anagrama1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnNuevaOfi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbOcu;
    private javax.swing.JComboBox cbOficina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbCompleto;
    private javax.swing.JRadioButton rbParcial;
    private javax.swing.JTextField txtDispo;
    private javax.swing.JFormattedTextField txtFcad;
    private javax.swing.JFormattedTextField txtFofe;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPalabras;
    private javax.swing.JTextField txtRango;
    // End of variables declaration//GEN-END:variables
}
